### ISSUE TITLE
EnsembleRegressor

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#10]
I opened this issue as a follow up on a discussion with 

@nikhilRP:

> Can we have some thing like "VotingClassifier" for regression as well.

 I believe the same concept would also work for regression from a technical perspective. However, I am not sure how "good" or "practical" this would be. I think one would have to be especially careful with the averaging if there is a high gap between the predicted targets, e.g., if we have 3 regressors with predicted targets of e.g., 1.1, 1.3, 1031.4, averaging could yield some strange behavior. Maybe it would be worthwhile to include some optional outlier detection. Here are some examples
1. for < 10 regressor, use Dixon's Q test to remove lower-end outliers 
2. for >= 10 regressor, maybe exclude everything what's outside the IQR (if the predicted scores are represented as a "box plot")
3. as an alternative to 1. and 2., use sequential feature selection to select a k-sized subset of regressors so that the performance of the average fit is "optimal."

I believe that an implementation would be pretty straight-forward from a technical perspective using the Ensemble Classifier as a template.

In addition, an interesting idea by @nikhilRP was 

> [to] use r-squared scores (or any other measure) to determine weights of each predicted targets.

Honestly, I haven't really thought about it, yet, and I suggest that we brainstorm a bit more. However, **in order to get started** we could already prepare a scaffold `EnsembleRegressor` that takes scikit-learns regressors as input estimators and outputs the average fits (similar to the `EnsembleClassifier`'s `predict_proba`). :)

**Note** 

The `mlxtend` is currently being slightly overhauled (see branch [https://github.com/rasbt/mlxtend/tree/03](https://github.com/rasbt/mlxtend/tree/03)). 

The `mlxtend.classifier.EnsembleClassifier` from the `mlxtend.classifier.ensemble.py` module has been moved to the `mlxtend.classifier.ensemble_vote.py` module where it is now `mlxtend.classifier.EnsembleVoteClassifier`. The reason is that the new "description" is more specific and would help distinguishing it from a future`mlxtend.classifier.EnsembleStackingClassifier` etc.
Furthermore, the `regression` subpackage has been split into 2 new subpackages `regressor` and `regression_utils` -- The former contains classes (estimators) for fitting regression models, and the latter contains auxiliary functions such as visualization tools etc.

I am preparing the new documentation and website right now, and the new release (v. 0.3) will probably ready next week and ready to be merged into the current master branch.

Thus, an `EnsembleRegressor` would best fit into the `mlxtend.regressor` subpackage.

**Comment by rasbt** [comment]
@nikhilRP Btw. I forgot to ask: Did you come across some publications about approaches that people already successfully (or not so successfully) tried?

**Comment by rasbt** [comment]
Regarding the overhaul mentioned above: v0.3.0 has been merged today. So, I'd suggest putting the `EnsembleRegressor` into `mlxtend/regressor/ensemble_regressor.py`

Depending on how we decide to implement it, we'd probably want to think about a more specific name instead of just `EnsembleRegressor` ...

**Comment by nikhilRP** [comment]
@rasbt  Sorry for the delay on taking a look at this.

After exhausting few techniques such a voting, bagging ans stacking using Constrained least squares etc I realized that  Feature weighted linear stacking (FWLS - http://arxiv.org/pdf/0911.0460.pdf) is still best out there in the wild. 

I also saw that there is no good implementation of FWLS for now (in python). May be we can start with basic stacking regressor with Least squared and then extend it to different strategies. (Constrained Least square, FWLS etc)

**Comment by rasbt** [comment]
No worries, @nikhilRP (sorry, but I am actually glad that it took some time because it's really busy around here :P). The paper looks cool, I haven't read it completely, yet, but their proposed idea only makes sense; it would be great to see this in action :). Btw. I just setup such a basic `StackingRegressor` that we could use as template (#12) . I'd suggest not to generalize the code, yet, but just use it a template that can be extended to the FWLS (makes debugging easier for the first implementation).

**Comment by theiling** [comment]
Hello,
I really like your style and the willingness to teach others as shown in the documentation.
https://github.com/rasbt/mlxtend/blob/master/docs/sources/user_guide/regressor/StackingRegressor.ipynb
For the Stacking regressor I was wondering why the gridsearch get's worse results than in the first example. I thought it should be at least the same results and tried it.
If you change it to below mentioned params the Stacking regressor gridsearch gets better results.

params = {'ridge__alpha': [0.8, 1.0, 10.0],
          'svr__C': [0.1, 0.5, 1.0],
          'meta-svr__C': [0.1, 0.5, 1.0, 5.0]}

I observed also an error first as the Ridge regresssor had no random_state param in my scikit, but this is probably an too old scikit-version(Version '0.16.1'). Deleting random_state and using ridge = Ridge() did work.

Bye the way: Great book! The typos make the errata quite long though and for the printed book I need to have a look at that errata file first.

**Comment by rasbt** [comment]
Hi @theiling I am really behind regarding my emails ... Just got a chance to work my way further done the stack ... you are right, the performance looks odd in comparison -- just a bad parameter grid, because I only had a technical demonstration in mind. However, I just updated the documentation nonetheless, thanks! Also thanks for the nice words regarding the book! Their was a recent revision and I hope all the errata errors had been fixed. I think if you got the printed book via Packt, they'll send you a new copy for free (based on what I've heard from other readers) :).

**Comment by sashml** [comment]
@rasbt can you please help me to understand this one - http://stats.stackexchange.com/questions/270958/why-stackerregressor-doesnt-catch-the-trend ? Sorry, for the off-top.

**Comment by rasbt** [comment]
Hi,
just looking at the plot via the link you provided, the problem is that your first level classifiers are all linear. And since the best fit through a function like `np.sin(X).ravel() * np.cos(X).ravel()` will be a straight line (since the function is symmetric), it will pass sth linear to the meta-classifier. 
If you want to fit such a function, you'd need to provide at least non-linear classifier as input to the StackingClassifier (e.g., I bet changing the first SVR to a RBF kernel SVR would do the job). 

Also, I bet  you could observe the same phenomenon (the straight line) if you just do 

```python
svr_rbf.fit(X, y) 
svr_rbf.predict(X)
```

**Comment by sashml** [comment]
Appreciate for the help!
