### ISSUE TITLE
Use all probabilities in StackingClassifier instead of averaging

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#100]
Use all level-1 class probabilities to train the second level classifier instead of averaging probabilities for each classifier, which should provide more information to the second-level classifier (as suggested in #29)

Paper Reference: Ting, Kai Ming, and Ian H. Witten. "Issues in stacked generalization." J. Artif. Intell. Res.(JAIR) 10 (1999): 271-289.

**Comment by chkoar** [comment]
Yeap. Averaging will be optional or will it be deprecated?

**Comment by rasbt** [comment]
> Yeap. Averaging will be optional or will it be deprecated?

Hm, I think it would be best to add a temporary parameter, `average_probas` and set it to `True` for now but deprecate it. In future, we then may want to set it to `False` and/or remove it completely. Reminds me that I need to add utilities for implementing these deprecation warnings (#29)

**Comment by shaypal5** [comment]
Hey,

I don't want to open this issue, just help me understand something I'm misunderstanding:

In your first post on this issue you wrote

> Use all level-1 class probabilities to train the second level classifier instead of averaging probabilities for each classifier...

Which already intuitively sounds weird to me; wouldn't you want to average the probabilities per possible class/label over all classifiers, and not get the average for each classifier?

Also, that what the code seems to be doing, right?
```
probas = np.asarray([clf.predict_proba(X) for clf in self.clfs_])
if self.average_probas:
    vals = np.average(probas, axis=0)
```

So, I just love to know whether I'm misunderstanding the text, or the intuition and the code.

Cheers,
Shay

**Comment by rasbt** [comment]
Thanks for the comment!

When I see it correctly, this is referring to the StackingClassifier, not the StackingCVClassifier, right?
I think the sentence you quoted sounds a bit weird, indeed. I think the example that follows the sentence kind of explains it, but I would welcome a PR to improve the docs.

So what happens is that the probabilities among the classifiers are averaged, not the probabilities within a classifier. For example, if we have 4 classifiers for the 3-class iris dataset, not-averaging (i.e., stacking) would lead to 12 meta feature columns (each classifier would return a probability for each of the 3 classes). If we set `average_probas=True`, we get only 3 meta-feature columns; here, all class 1 probabilities (4, because we have 4 classifiers) get averaged, all class 2 probas get averaged, and all class 3 probas get averaged.
