### ISSUE TITLE
from mlxtend.plotting import heatmap not running in google colab

### ISSUE THREAD

**Issue by andysingal** [rasbt/mlxtend#1032]
Hi Sabastian,
        Thanks for the amazing library, i am having the following challenge running in google colab
```
from mlxtend.plotting import heatmap

cm = np.corrcoef(df.values.T)
hm = heatmap(cm, row_names = df.columns, column_names = df.columns, figsize = (20, 20))
plt.title('Correlations Between the Different Features of the Data', fontsize = 20)
plt.show()
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-38-66b9ffa3ca9c>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 cm = np.corrcoef(df.values.T)
----> 4 hm = heatmap(cm, row_names = df.columns, column_names = df.columns, figsize = (20, 20))
      5 plt.title('Correlations Between the Different Features of the Data', fontsize = 20)
      6 plt.show()

TypeError: 'module' object is not callable
```
I was not able to find anyone with same error.
I have already tried :
!pip uninstall mlxtend
and installing:
!pip install git+git://github.com/rasbt/mlxtend.git
with no success.
Looking forward to hearing from you.
Thanks,
Ankush Singal

**Comment by rasbt** [comment]
I think this may be a version issue (like here: https://github.com/rasbt/mlxtend/issues/939)

**Comment by andysingal** [comment]
Still the same issue, scatterplot works fine, the problem is with heatmap as shown in the pic below.
I also tried : 
%%capture
!pip install mlxtend --upgrade
with no success
<img width="805" alt="Screen Shot 2023-04-27 at 10 54 26 PM" src="https://user-images.githubusercontent.com/20493493/234941287-d0b045d9-8ed5-4dea-8097-03267e15a6f1.png">

**Comment by rasbt** [comment]
Hm, sorry, that's weird. I honestly don't have a good explanation for this. I just tried it myself and it seems to work. Maybe restart and try again?
<img width="1255" alt="Screenshot 2023-04-27 at 3 00 51 PM" src="https://user-images.githubusercontent.com/5618407/234977641-50159529-5b79-450d-8fe9-5dda954dc5b8.png">

**Comment by andysingal** [comment]
Works now, i added:
import mlxtend
<img width="922" alt="Screen Shot 2023-04-28 at 7 56 49 AM" src="https://user-images.githubusercontent.com/20493493/235039729-84126de5-9ec1-48be-9f62-1f60d9c5f79d.png">
