### ISSUE TITLE
Adding more metrics for Association Rules

### ISSUE THREAD

**Issue by UltraArceus3** [rasbt/mlxtend#1096]
### Discussed in https://github.com/rasbt/mlxtend/discussions/1031

<div type='discussions-op-text'>

<sup>Originally posted by **Nachiket18** April 24, 2023</sup>
There are several metrics like lift, leverage, conviction etc are available for association rules. Wondering if it would be of help if we implement other metrics like Jaccard, Added Value, Certainty Factor etc. </div>

We are planning on implementing more Association Rules metrics from this resource: https://mhahsler.github.io/arules/docs/measures
Metrics we are currently considering are: Jaccard Coefficient, Certainty Factor, and Added Value.

![image](https://github.com/rasbt/mlxtend/assets/25268334/f69d0fa5-1ee0-490d-aa71-afb68ba0030a)
![image](https://github.com/rasbt/mlxtend/assets/25268334/90e83305-b23b-4b44-8eff-7ec03c6153d9)
![image](https://github.com/rasbt/mlxtend/assets/25268334/95b79e44-daa1-46df-81e8-d63d08a7081e)

**Comment by Nachiket18** [comment]
1. We were able to implement the _Jaccard_ similarity (https://github.com/UltraArceus3/mlxtend/blob/master/mlxtend/frequent_patterns/association_rules.py#L133)
2. We tested the code with an sample example (https://github.com/UltraArceus3/mlxtend/blob/master/mlxtend/frequent_patterns/tests/test_association_rules.py#L181)

@rasbt - Could you share your thoughts about this?  We have also implemented _Certainty Factor_ and _Centered Confidence_ for which we would be writing test cases.

**Comment by rasbt** [comment]
H @UltraArceus3  and @Nachiket18 . Thanks for suggesting these and offering to help implementing these! On my end, I am currently very maxed out with other projects and wouldn't have the capacity to contribute anything at the moment. However, I could approve PRs etc in case you want to contribute these. (Sorry that I can't be more helpful at the moment, but my free time is mostly taken up by my LLM from Scratch book until mid July; but I am happy to approve PRs, and I actually really appreciate your willingness to contribute).
