### ISSUE TITLE
Formatting on file_io.find_files parameters is off on the documentation website

### ISSUE THREAD

**Issue by KPLauritzen** [rasbt/mlxtend#117]
Documentation: http://rasbt.github.io/mlxtend/user_guide/file_io/find_files/#api

The parameters `recursive` and `check_ext` are not formatted as individual parameters but are instead in the same bullet point as `path`.

**Comment by rasbt** [comment]
Good catch, thanks! That was due to a missing whitespace before the colon. Will fix that with a PR.
