### ISSUE TITLE
Segmentation fault on plotting confusion matrix!

### ISSUE THREAD

**Issue by spate141** [rasbt/mlxtend#152]
I am trying to plot confusion matrix of 1000 labels and save it to a picture file. After using 15GB of memory, code is terminating with segmentation fault! Any reason?

**Comment by rasbt** [comment]
Hm, that's weird ... Do you have a example snippet to reproduce this issue?

**Comment by spate141** [comment]
cmt = `confusion_matrix` of 1000x1000 `<type 'numpy.ndarray'>`

and here the part where I am trying to save plot:
```
fig, ax = plot_confusion_matrix(conf_mat=cmt, figsize=(50,50))
fig.savefig('results.jpg')
```

**Comment by rasbt** [comment]
50 x 50 is pretty large. Technically, it should work, but maybe that's why it's eating up your memory. For debugging purposes, could you try figsize=(10,10) or so?

**Comment by spate141** [comment]
Same thing.. segmentation fault with (10,10) and or with default values of (2.5, 2.5)!

**Comment by rasbt** [comment]
Hm, I believe that's due to the many text labels in the plot (1000 * 1000 = 1,000,000); it's probably more than matplotlib can handle on a desktop computer. E.g., if I am just trying to execute the following, I get a similar memory prob:

```
import numpy as np
import matplotlib.pyplot as plt

ary = (np.random.sample((1000, 1000)) * 1000).astype(int)
plt.table(cellText=ary, loc='center')
plt.show()
```

I don't have a good solution for that in mind, unfortunately.

**Comment by spate141** [comment]
Aha.. I see. Anyway, thank you for the quick replies.
