### ISSUE TITLE
Fix typo for autompg and wine data

### ISSUE THREAD

**Issue by jrbourbeau** [rasbt/mlxtend#165]
I noticed a couple (very minor) typos in the wine and autompg dataset documentation. In the example on the wine dataset documentation there is the following line:
```
print('\nHeader: %s' % ['sepal length', 'sepal width',
                        'petal length', 'petal width'])
```
These are the features for the iris dataset, not the wine dataset. In addition, in the autompg there is a feature listed as `'horsepower weight'`, but should be two separate features `'horsepower', 'weight'`

**Comment by rasbt** [comment]
This has been addressed in #167 . Thanks for the PR @jrbourbeau
