### ISSUE TITLE
getting a 'ValueError: all the input arrays must have same number of dimensions" only for CV

### ISSUE THREAD

**Issue by subratac** [rasbt/mlxtend#170]
Hi,

Thanks for the nice program. I am trying to use it for stacking and started with the CV version but can't seem to make it work.

I am passing X & Y as below. They have the right shape and the code runs for the two classifiers clf1 and clf2. however, it hits a snag when it does the meta classifier. It complains: 

***ValueError: all the input arrays must have same number of dimensions***

I don't understand this since the arrays have the right dimensions: 
X = (49352, 217)
y =  (49352,)

Could someone help? Thanks!
Sub

Here's the code:
======
clf1 = KNeighborsClassifier(n_neighbors=1)
clf2 = RandomForestClassifier(random_state=1)
#clf3 = GaussianNB()
lr = LogisticRegression()
gb = xgb.XGBClassifier( learning_rate =0.1, n_estimators=1000, max_depth=5, min_child_weight=1,\
                         gamma=0,subsample=0.8,colsample_bytree=0.8,objective= 'multi:softprob',\
                         nthread=4,scale_pos_weight=1,seed=27)

sclf = StackingCVClassifier(classifiers=[clf1, clf2],
                            use_probas=True,
                            meta_classifier=gb,
                            random_state=42)

X = train_X
y = train_y

print(train_X.shape,train_y.shape)

print('3-fold cross validation:\n')

for clf, label in zip([clf1, clf2, sclf], 
                      ['KNN', 
                       'Random Forest', 
                       'StackingClassifier']):

    scores = model_selection.cross_val_score(clf, X, y, 
                                              cv=3, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" 
          % (scores.mean(), scores.std(), label))

=========== OUTPUT BELOW ====

(49352, 217) (49352,)

3-fold cross validation:

Accuracy: 0.59 (+/- 0.01) [KNN]
Accuracy: 0.71 (+/- 0.00) [Random Forest]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-147-2ac93725e0ab> in <module>()
     29 
     30     scores = model_selection.cross_val_score(clf, X, y, 
---> 31                                               cv=3, scoring='accuracy')
     32     print("Accuracy: %0.2f (+/- %0.2f) [%s]" 
     33           % (scores.mean(), scores.std(), label))

C:\Users\tickles\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py in cross_val_score(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch)
    138                                               train, test, verbose, None,
    139                                               fit_params)
--> 140                       for train, test in cv_iter)
    141     return np.array(scores)[:, 0]
    142 

C:\Users\tickles\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in __call__(self, iterable)
    756             # was dispatched. In particular this covers the edge
    757             # case of Parallel used with an exhausted iterator.
--> 758             while self.dispatch_one_batch(iterator):
    759                 self._iterating = True
    760             else:

C:\Users\tickles\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in dispatch_one_batch(self, iterator)
    606                 return False
    607             else:
--> 608                 self._dispatch(tasks)
    609                 return True
    610 

C:\Users\tickles\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in _dispatch(self, batch)
    569         dispatch_timestamp = time.time()
    570         cb = BatchCompletionCallBack(dispatch_timestamp, len(batch), self)
--> 571         job = self._backend.apply_async(batch, callback=cb)
    572         self._jobs.append(job)
    573 

C:\Users\tickles\Anaconda3\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py in apply_async(self, func, callback)
    107     def apply_async(self, func, callback=None):
    108         """Schedule a func to be run"""
--> 109         result = ImmediateResult(func)
    110         if callback:
    111             callback(result)

C:\Users\tickles\Anaconda3\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py in __init__(self, batch)
    324         # Don't delay the application, to avoid keeping the input
    325         # arguments in memory
--> 326         self.results = batch()
    327 
    328     def get(self):

C:\Users\tickles\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in __call__(self)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132 
    133     def __len__(self):

C:\Users\tickles\Anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in <listcomp>(.0)
    129 
    130     def __call__(self):
--> 131         return [func(*args, **kwargs) for func, args, kwargs in self.items]
    132 
    133     def __len__(self):

C:\Users\tickles\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py in _fit_and_score(estimator, X, y, scorer, train, test, verbose, parameters, fit_params, return_train_score, return_parameters, return_n_test_samples, return_times, error_score)
    236             estimator.fit(X_train, **fit_params)
    237         else:
--> 238             estimator.fit(X_train, y_train, **fit_params)
    239 
    240     except Exception as e:

C:\Users\tickles\Anaconda3\lib\site-packages\mlxtend\classifier\stacking_cv_classification.py in fit(self, X, y)
    187                                                y[test_index]))
    188             reordered_features = np.concatenate((reordered_features,
--> 189                                                  X[test_index]))
    190 
    191         # Fit the base models correctly this time using ALL the training set

**ValueError: all the input arrays must have same number of dimensions**

**Comment by rasbt** [comment]
Hi,
I just ran the code using the `GaussianNB` instead of `XGBoost`, and it seems to be working fine. The full code is

```python
from mlxtend.data import iris_data
from mlxtend.classifier import StackingCVClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score

X, y = iris_data()

clf1 = KNeighborsClassifier(n_neighbors=1)
clf2 = RandomForestClassifier(random_state=1)
clf3 = GaussianNB()

#gb = xgb.XGBClassifier( learning_rate =0.1, n_estimators=1000, max_depth=5, min_child_weight=1,
#gamma=0,subsample=0.8,colsample_bytree=0.8,objective= 'multi:softprob',
#nthread=4,scale_pos_weight=1,seed=27)

sclf = StackingCVClassifier(classifiers=[clf1, clf2],
use_probas=True,
meta_classifier=clf3,
random_state=42)

for clf, label in zip([clf1, clf2, sclf], 
                      ['KNN', 'Random Forest', 'StackingClassifier']):

    scores = cross_val_score(clf, X, y, 
                             cv=3, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" 
          % (scores.mean(), scores.std(), label))
```



I suspect there's maybe an incompatibility with the `xgb.XGBClassifier`. What do you get if you just run the  last part, with XGBoost instead of the `StackingCVClassifier`?

```python
for clf, label in zip([clf1, clf2, sclf], 
                      ['KNN', 'Random Forest', 'StackingClassifier']):

    scores = cross_val_score(clf, X, y, 
                             cv=3, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" 
          % (scores.mean(), scores.std(), label))
```

Also, could you check the output of `sclf.fit(X, y).predict(X).shape`? It should return `(49352,)` on your dataset.

**Comment by subratac** [comment]
Thanks Sebastian for the quick reply. 

1) I also checked and the code runs with the Iris dataset example. 

2) I also ran the XGBboost only as per your suggestion by NOT including the Stacking VCClassifier and the output below. So, XGboost runs okay by itself. 

3-fold cross validation:

Accuracy: 0.59 (+/- 0.01) [KNN]
Accuracy: 0.71 (+/- 0.00) [Random Forest]
Accuracy: 0.75 (+/- 0.00) [Xgboost]

=====

3) I also checked the shape using gb.fit(X, y).predict(X).shape and it returned (49352,) . 

4) To determine if Xgboost is incompatible, I swapped it with Decision tree as below. It runs fine. You are correct, the mlxtend code is not compatible with XGboost. 

clf1 = KNeighborsClassifier(n_neighbors=1)
clf2 = RandomForestClassifier(random_state=1)
#clf3 = GaussianNB()
#lr = LogisticRegression()

from sklearn.tree import DecisionTreeClassifier
sclf = DecisionTreeClassifier(max_depth= 5)



target_num_map = {'high':0, 'medium':1, 'low':2}
train_y = np.array(train_df['interest_level'].apply(lambda x: target_num_map[x]))
#train_y = train_df['interest_level'].apply(lambda x: target_num_map[x])


X = train_X
y = train_y

print('3-fold cross validation:\n')

for clf, label in zip([clf1, clf2,sclf], 
                      ['KNN', 
                       'Random Forest', 
                       'DTree']):

    scores = model_selection.cross_val_score(clf, X, y, 
                                              cv=3, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" 
          % (scores.mean(), scores.std(), label))
=============

3-fold cross validation:

Accuracy: 0.59 (+/- 0.01) [KNN]
Accuracy: 0.71 (+/- 0.00) [Random Forest]
Accuracy: 0.71 (+/- 0.00) [DTree]

**Comment by rasbt** [comment]
Thanks for the additional info! I remember @rhiever mentioned once that XGBoost was a bit tricky to use in of [TPOT](https://github.com/rhiever/tpot), but it looks like it's supported now.

Have to look into this more, but it looks like your problem may have something to do with the parallel processing. 

Could you maybe try to run XGBoost with `nthreads=1` and see if that works? (Have to install and play with XGBoost myself this weekend)

**Comment by rasbt** [comment]
Just ran it on my macbook with

```python
gb = xgb.XGBClassifier(learning_rate =0.1, n_estimators=1000, 
                       max_depth=5, min_child_weight=1,
                       gamma=0,subsample=0.8,
                       colsample_bytree=0.8,objective= 'multi:softprob',
                       nthread=4,scale_pos_weight=1,seed=27)

sclf = StackingCVClassifier(classifiers=[clf1, clf2],
                            use_probas=True,
                            meta_classifier=gb,
                            random_state=42)
```
and it seems to work fine. So it's probably something about that multi-threading that is causing issues here (I think -- according to the xgboost docs -- my macbook may not support multithreading in XGBoost)

**Comment by subratac** [comment]
Hi Sebastian,
Did a quick run with nthread = 1 , but still getting the same error. Will take a look again tomorrow.Appreciate your help in this matter.BestSub

**Comment by rhiever** [comment]
@subratac, did you try installing XGBoost *without* multithreading support? I know, a bit of a pain, but that could be part of the issue.

**Comment by subratac** [comment]
Agree. re-installing Xgboost is probably the only option and it's a HUGE pain to install. The last time I installed it, it required compiling and all that nice stuff. Could not do a straight pip install.

**Comment by rasbt** [comment]
yeah, same here. Wasn't a huge pain though as it compiled fine, but I am wondering about the purpose of the pip package (doesn't work for me either) ...  ;)

**Comment by rhiever** [comment]
I've seen xgboost pip install fine on Linux before. But Macs generally struggle.

**Comment by rasbt** [comment]
ah, I just see that they don't use Python wheels for some reasons ...

**Comment by rasbt** [comment]
On my Linux machine (CentOS) it's even worse

```make: *** [build/learner.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [build/logging.o] Error 1
make: *** [build/c_api/c_api.o] Error 1
make: *** [build/c_api/c_api_error.o] Error 1
```

no clue how to install it :confused:

**Comment by rhiever** [comment]
Hmm. Funny enough, I was able to install the latest version of XGBoost on both Mac and Linux this morning with a simple `pip install xgboost --no-cache`.

**Comment by subratac** [comment]
I am running Anaconda on a Windows machine & pip does not work for Xgboost. I use the Github version and compile.

**Comment by rhiever** [comment]
Oh, Windows is another story. Much harder to support for multiprocessing.

**Comment by rasbt** [comment]
> Hmm. Funny enough, I was able to install the latest version of XGBoost on both Mac and Linux without issue this morning with a simple pip install xgboost --no-cache.

Interesting! I just gave it a try on an AWS Ubuntu instance, installing it via pip after having just miniconda installed. It successfully installed the requirements (numpy, scipy, sklearn), but then it failed at XGBoost. However, if I install numpy, scipy, sklearn via conda, then run the `pip install xgboost`, it builds wheels and everything works fine. 

```
Building wheels for collected packages: xgboost
  Running setup.py bdist_wheel for xgboost ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/5e/c1/d6/522af54e5cc001fad4dd855117f8bf61b11d56443e06672e26
Successfully built xgboost
Installing collected packages: xgboost
Successfully installed xgboost-0.6a2
```

**Comment by rasbt** [comment]
PS: It also seems to work fine with XGBoost in the StackingCVClassifier and multithreading enabled (`nthreads=4`). So I guess it unfortunately really is a Windows issue with multi-processing?!

**Comment by npetrenko** [comment]
I've experienced the same error. This problem comes when you try to feed a sparse matrix instead of a dense one. I see that your lib doesn't support scipy.sparse yet

**Comment by rasbt** [comment]
Thanks for the note @npetrenko . I will add issues to at scipy.sparse support to the stacking classifiers/regressors ... and I'd welcome PRs of course :)

**Comment by rasbt** [comment]
I think this is fixed now
