### ISSUE TITLE
plot_decision_regions import statement incorrect in manual

### ISSUE THREAD

**Issue by dickienaut** [rasbt/mlxtend#174]
Noticed that page 18 line 1 of the user manual specifies the import for plot_decision_regions as:
from mlxtend.evaluate import plot_decision_regions
This fails to import for me.

I got it working with:
from mlxtend.plotting import plot_decision_regions

Thanks!

**Comment by rasbt** [comment]
Thanks for the heads up! Just noticed that I forgot to update the PDF documentation for a while. Will add it to my make-a-new-release checklist so that I won't forget next time. Should be fixed now :)
