### ISSUE TITLE
ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

### ISSUE THREAD

**Issue by ErmiaAzarkhalili** [rasbt/mlxtend#180]
Hi.
It seems there existed new issues related to tflearn.
it can be seen [here](https://github.com/tflearn/tflearn/issues/639).
it will happen when you call both Tfsoftamxregression and tfmultilayerpreceptron.

Could you please check it out to resolve the issue, I think the error is related to tensorflow itself though.

**Comment by rasbt** [comment]
Thanks for the note. I think that's due to the recent changes in Tf 1.1.0 (unrelated to Tflearn). I am thinking about removing these tensorflow functions in mlxtend entirely, since there's an Estimator class in TensorFlow now that would make them kind of non-relevant anymore.

**Comment by rasbt** [comment]
addressed in #182
