### ISSUE TITLE
Plot decision regions user guide not updated in 0.7 release

### ISSUE THREAD

**Issue by jrbourbeau** [rasbt/mlxtend#207]
Hey @rasbt, I noticed that the API documentation page for the `plot_decision_regions` function was updated in the 0.7 release in accordance with PR #189, but the user guide information (http://rasbt.github.io/mlxtend/user_guide/plotting/plot_decision_regions/) was not updated. The updates I made to the user guide (examples 7 and 8 in https://github.com/rasbt/mlxtend/blob/master/docs/sources/user_guide/plotting/plot_decision_regions.ipynb) made it into the master branch, but somehow didn't make it to the documentation page. I'm not sure if I missed something in PR #189 that made the user guide updates not get updated with the documentation page.

**Comment by rasbt** [comment]
Thanks for the note. It looks like the web changes haven't been pushed correctly. I will take care of that tonight or this weekend. Thanks for the note!
