### ISSUE TITLE
How does the prediction work in StackingCVRegressor & StackingCVClassifier

### ISSUE THREAD

**Issue by unfashionable** [rasbt/mlxtend#236]
In the cross validation version of stacking models (I'm refering to your flowchart: https://rasbt.github.io/mlxtend/user_guide/regressor/StackingCVRegressor_files/stacking_cv_regressor_overview.png), the number of trained models should be #base_model * #CV + 1 meta-model, right?

But when you predict X, which base models will you use? Because you trained based models on different subset of the data, this really confused me.

Thank you!

**Comment by rasbt** [comment]
Yes, to create the meta features for the meta-model, "#base_model * #CV" models are effectively trained. However, once the meta-model is fit to the meta-features, the base models are refit to the original training data, i.e., we have #base_models in the end for prediction, not "#base_model * #CV".

To summarize the procedure in pseudo code:

---

1) train the number of trained regressors is: base-regressors * cv_folds  

For each base regressor b:   
    For iteration in cross-validation:   
        fit b to training k-1 folds (training folds)  
        use b to make prediction on the kth fold (holdout fold); aka meta feats  

2) use meta feats to fit level 2 regressor ('meta regressor')  

3) fit each base regressor to the original data

---  

I hope this answers your question :)

**Comment by unfashionable** [comment]
It is very helpful! 
Thank you!
