### ISSUE TITLE
doubt: mlxtend on top of tpot

### ISSUE THREAD

**Issue by HaraldHeitmann** [rasbt/mlxtend#282]
Hi!
I have the following doubt:
Can I use mlxtend on top of  tpot https://github.com/rhiever/tpot.
like, fitting the metaparameters with tpot, and then building and ensemble model with mlxtend?
If I'm missing something obvious please tell me
nice project btw

**Comment by rasbt** [comment]
Haven't tried it myself, but I remember that there was a recent discussion about this. Maybe that's helpful: https://github.com/rhiever/tpot/issues/152

**Comment by HaraldHeitmann** [comment]
Thanks,
Gonna take a look, and try by myself when I have some more spare time, I'll reach out here if I got something interesting out of it

**Comment by rasbt** [comment]
Closing this for now, but pls let me know if you have any further comments!
