### ISSUE TITLE
mlxtend/scipy compatibility issues?

### ISSUE THREAD

**Issue by hedgy123** [rasbt/mlxtend#284]
Hi,

   I am using the most recent versions of mlxtend and scipy, and I am getting the error below that might stem from the fact that scipy.stats.chisqprob has been replaced by scipy.distributions.chi2.sf.  Would it be possible to update mlxtend?  Thanks so much!

    ImportError                               Traceback (most recent call last)
      <ipython-input-275-a1fcea6b2827> in <module>()
            5 print("scipy verson = ",scipy.__version__)
            6 #from scipy.stats import chisqprob
      ----> 7 from mlxtend.evaluate import lift_score
            8 
            9 

    D:\Anaconda3\lib\site-packages\mlxtend\evaluate\__init__.py in <module>()
          8 from .confusion_matrix import confusion_matrix
          9 from .lift_score import lift_score
    ---> 10 from .mcnemar import mcnemar_table
         11 from .mcnemar import mcnemar
         12 from .bootstrap import bootstrap

    D:\Anaconda3\lib\site-packages\mlxtend\evaluate\mcnemar.py in <module>()
          7 
          8 import numpy as np
    ----> 9 from scipy.stats import chisqprob
         10 from scipy.stats import binom
         11 

    ImportError: cannot import name 'chisqprob'

**Comment by rasbt** [comment]
Thanks for the note. I stumbled upon the same problem recently, and it should already be fixed it in the master branch: https://github.com/rasbt/mlxtend/blob/bb5ff709e584bbdf2c0fcfe594ac9746fc54ca80/mlxtend/evaluate/mcnemar.py#L104

Will make a new release some time

**Comment by rasbt** [comment]
Just pushed a new release yesterday (v0.9.1) to PyPI and conda-forge. It should fix the problem if you are not using the dev versions.
