### ISSUE TITLE
Raise meaningful error messages if the Stacking(CV)Regressor/Classifiers haven't been fit

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#289]
Raise meaningful error messages if the Stacking(CV)Regressor/Classifiers haven't been fit and the predict method is called. See #286

**Comment by jrbourbeau** [comment]
It's possible that this issue can be closed now. It looks like the Stacking(CV)Regressor/Classifiers all raise `NotFittedError` when `predict`, `predict_meta_features`, etc. are called before `fit`. 

StackingRegressor:
https://github.com/rasbt/mlxtend/blob/bac2d268102da03126815e0e1c8d73c7986c64b4/mlxtend/regressor/stacking_regression.py#L186-L188

StackingCVRegressor:
https://github.com/rasbt/mlxtend/blob/bac2d268102da03126815e0e1c8d73c7986c64b4/mlxtend/regressor/stacking_cv_regression.py#L206-L208

StackingClassifier:
https://github.com/rasbt/mlxtend/blob/bac2d268102da03126815e0e1c8d73c7986c64b4/mlxtend/classifier/stacking_classification.py#L217

StackingCVClassifier:
https://github.com/rasbt/mlxtend/blob/bac2d268102da03126815e0e1c8d73c7986c64b4/mlxtend/classifier/stacking_cv_classification.py#L294

**Comment by rasbt** [comment]
Thanks for checking into this! I just double-checked and it seems that not everything was "checked" (i.e., the `predict_meta_features` methods). I just cleaned it up a bit and addressed that in #353
