### ISSUE TITLE
How to perform more than 2-stage stacking using StackingClassifier?

### ISSUE THREAD

**Issue by NagabhushanS** [rasbt/mlxtend#292]
I wish to use a 3-layer stacking arrangement as follows:
Level 1: LogisiticRegression, DecisionTree, XGBoost
Level 2: SGDClassifier, XGBoost
Level 3: RandomForestClassifier

I wanted to know if the following setup would work as intended or not?

<i>

m1=LogisticRegression()

m2=DecisionTreeClassifier()

m3=XGBoostClassifier()

m4=SGDClassifier()

m5=XGBoostClassifier()

st1=StackingClassifier(classifiers=[m1, m2, m3], meta_classifier=m4)

st2=StackingClassifier(classifiers=[m1, m2, m3], meta_classifier=m5)

m6=RandomForestClassifier()

finalSt = StackingClassifier(classifiers=[st1, st2], meta_classifier=m6)

finalSt.fit(X, Y) </i>

Is the above setup correct or do I need to call fit method after each level like <i>st1.fit(X, Y), st2.fit(X, Y) </i> and then <i>finalSt.fit(X, Y)</i>?

**Comment by rasbt** [comment]
This should work as intended without having to call fit after each level. In the current implementation, clones of the input `classifiers` and `meta_classifier` arguments are fit inside the `StackingClassifier`. 

So what should happen when you call `finalSt.fit(X, Y)` is that its `classifiers` and `meta_classifier` are fit inside, and upon fitting `classifiers` and `meta_classifier`, their `classifiers` and `meta_classifier` inside should be fit in a recursive manner.

Hope that helps

**Comment by NagabhushanS** [comment]
Ok..So it means that that the fit methods are called in a recursive way and it suffices to call fit only on the last layer classifier.

**Comment by rasbt** [comment]
Yes, theoretically, this is what should happen :)
