### ISSUE TITLE
Error when fitting a StackingCVClassifier. (Add support for sparse matrices/arrays)

### ISSUE THREAD

**Issue by NagabhushanS** [rasbt/mlxtend#293]
I am getting an error when I executed the following code:

<i>
#X is an array of strings and Y is the set of labels for classification

model1=LogisticRegression()
model2=DecisionTreeClassifier()

model3=LogisticRegression()

sclf = StackingCVClassifier(classifiers=[model1, model2],
                            meta_classifier=model3)

model = Pipeline([('vect', HashingVectorizer(ngram_range=(1, 1))),
                      ('tfidf', TfidfTransformer(use_idf=True)),
                     ('classifier', sclf),
])

X = np.array(X)
Y = np.array(Y)

model.fit(X, Y)

</i>

When I replace <i>sclf </i> with <i>LogisticRegression() </i>, the error is gone. Following is the error trace:

<i><b>
Traceback (most recent call last):
  File "best.py", line 80, in <module>
    model.fit(X, Y)
  File "C:\Users\nagabhushan.s\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\sklearn\pipeline.py", line 250, in fit
    self._final_estimator.fit(Xt, y, **fit_params)
  File "C:\Users\nagabhushan.s\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\mlxtend\classifier\stacking_cv_classification.py", line 215, in fit
    X[test_index]))
ValueError: all the input arrays must have same number of dimensions
</b></i>

**Comment by rasbt** [comment]
Just took a quick look at it and there seem to be at least two types of issues. 

1) The `StackingCVClassifier` currently doesn't support sparse matrices, so you would need to insert "to-dense" transformers after the `HashingTransformer` and `TfidfTransformers`. 

2) Not sure if this was an issue in your case, but another error occurs of the "Y" array is not a NumPy array.

Below is an example of some working code incl. the use of the `DenseTransformer`s:

```python
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

from mlxtend.preprocessing import DenseTransformer
from mlxtend.classifier import StackingCVClassifier
#from mlxtend.classifier import StackingCVClassifier


corpus = [
         'This is the first document.',
         'This is the second second document.',
         'And the third one.',
         'Is this the first document?',
         'This is the first document.',
         'This is the second second document.',
         'And the third one.',
         'Is this the first document?']

Y = np.array([1, 1, 0, 0, 1, 1, 0, 0])

model1 = LogisticRegression()
model2 = DecisionTreeClassifier()
model3 = LogisticRegression()


sclf = StackingCVClassifier(classifiers=[model1, model2], meta_classifier=model3)

model = Pipeline([
    ('vect', HashingVectorizer(ngram_range=(1, 1))),
    ('to_dense1', DenseTransformer()),
    ('tfidf', TfidfTransformer(use_idf=True)),
    ('to_dense2', DenseTransformer()),
    ('sgd', sclf),
    ])

model.fit(corpus, Y)
```

I hope this works for you. 

In any case, let me leave this issue open to remind me of implementing support for both Python list inputs (as Y arrays) and the sparse matrix support.

**Comment by NagabhushanS** [comment]
If StackingCVClassifier does not support sparse matrices, does StackingClassifier support sparse scipy matrices?

**Comment by rasbt** [comment]
Yes, it should work with sparse matrices.
