### ISSUE TITLE
Question - Different X for Different Classifiers

### ISSUE THREAD

**Issue by BrianMiner** [rasbt/mlxtend#316]
One of the best ways (I have found) for building stacking ensembles includes using different subsets of the training data (e.g. different transformations of X) in various models. Is this possible with mlxtend? So for example maybe the first model uses X, the second model uses X', the third uses X''

**Comment by rasbt** [comment]
I agree regarding using the different subsets. Reminds me of Zac Stewart's article years ago on feature unions (http://zacstewart.com/2014/08/05/pipelines-of-featureunions-of-pipelines.html). Unfortunately, no, mlxtend does not support it for stacking. However, the `EnsembleVoteClassifier` should be able to handle it if you set `refit=False` (it's not stacking though, just majority vote classification)

**Comment by BrianMiner** [comment]
Doesnt this actually do the exact thing? One could use more elaborate pipelines of course than just selecting columns...

https://rasbt.github.io/mlxtend/user_guide/classifier/StackingCVClassifier/#example-4-stacking-of-classifiers-that-operate-on-different-feature-subsets
