### ISSUE TITLE
couldn't generate rules for my transaction data

### ISSUE THREAD

**Issue by dspkgp** [rasbt/mlxtend#320]
I have added a new line of code in mlxtend.frequent_patterns.apriori.py
support[np.isnan(support)] = 0
since it was having NaN values in creating support (line 50) 
converted NaN values to 0 and rules were generated for my data

**Comment by dspkgp** [comment]
Please let me know if I'm right or not?

**Comment by rasbt** [comment]
Hm, that actually shouldn't happen in the `apriori` function. So basically, you got NaNs via `apriori` and then couldn't run the `frequent_patterns`? Could you maybe share an excerpt of the dataset that causes this issue? Maybe there's some other underlying issue, so that I can look into that and debug.

**Comment by dspkgp** [comment]
I got NaN value via apriori and couldn't generate rules (rules dataframe was empty). But after adding that line in apriori, I got the rules. Please let me know how could I send you the dataset.

**Comment by rasbt** [comment]
Oh I see. Maybe there was an issue with the parsing or the format somehow though. In either case, I'd be happy to take a look at it! 

If you are not comfortable sharing the data online, you can send me an email at mail@sebastianraschka.com -- I promise to not share it further! Alternatively, Dropbox or Google Drive would work as well if the file is too large for emailing.

Thanks!

**Comment by dspkgp** [comment]
Alright I'll send you the dataset by end of day.

**Comment by rasbt** [comment]
Just wondering, have you had a chance to figure out what was wrong with the apriori function and the NaN issue you mentioned?

**Comment by rasbt** [comment]
closing for now, since, almost a year old. Pls reopen if the issue persists
