### ISSUE TITLE
Add SparseDataFrame support for both apriori and association_rules

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#329]
Add SparseDataFrame support for both apriori and association_rules to decrease the memory footprint as suggested by @jaksmid in #298

(opening this as a separate issue so that we can keep #298 for a out-of-core learning discussion in future)

**Comment by DanielMorales9** [comment]
Hi everybody, I've written a sparse apriori version, you may find it useful. It makes use of scipy.sparse.csc_matrix. You can find it here: https://gist.github.com/DanielMorales9/a47569c4657cc1614054e076074bf2b7.

**Comment by rasbt** [comment]
That looks useful, thanks for sharing!

Would you consider adding this functionality to the one in mlxtend via a PR some time in future?

Best,
Sebastian

**Comment by DanielMorales9** [comment]
Should you close this issue or not?

**Comment by rasbt** [comment]
I think we can close that now, it doesn't really make sense to have the frequent itemset representation in a SparseDataFrame.
