### ISSUE TITLE
Change itemsets generated via `apriori`  from list to sets

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#344]
I think it would be good to change the itemset representation generated via `apriori` from a list representation to a set representation, i.e.,

![screen shot 2018-03-14 at 9 23 11 am](https://user-images.githubusercontent.com/5618407/37405580-6678ee24-276b-11e8-934c-75fa24e9f182.png)

   |
   |
   v

![screen shot 2018-03-14 at 9 31 36 am](https://user-images.githubusercontent.com/5618407/37405582-67d9a6b4-276b-11e8-8a20-bde91b5475ce.png)

For reasons discussed in #343

**Comment by WLaney** [comment]
If people are still on board with this enhancement I can take a stab at implementing it

**Comment by rasbt** [comment]
Thanks. I think it may be an improvement overall :) . (But could be that I am missing something.)

**Comment by WLaney** [comment]
Yeah I agree. I'll get to work implementing this

**Comment by rasbt** [comment]
addressed in #393
