### ISSUE TITLE
How to get StackingClassifier score

### ISSUE THREAD

**Issue by SimoCanc** [rasbt/mlxtend#359]
When I run this code:
```
lr = LogisticRegression()
np.random.seed(123)
sclf = StackingCVClassifier(classifiers=[text_clf_bayes, text_clf_svm],
                            use_probas=True,
                            meta_classifier=lr)

for clf, label in zip([text_clf_bayes, text_clf_svm, sclf], 
                      ['Naive Bayes',
                       'LinearSVM'
                       'StackingClassifier']):

    scores = model_selection.cross_val_score(clf, X_train, y_train, 
                                              cv=5, scoring='accuracy')
    print("Accuracy: %0.2f (+/- %0.2f) [%s]" 
          % (scores.mean(), scores.std(), label))
```

I don't get the _StackingClassifier_ score, why?

**Comment by jrbourbeau** [comment]
@SimoCanc you're right, this should return the cross-validated scores for each of the three classifiers. It looks like there's a comma that's missing in the `for` loop between the `'LinearSVM'` and `'StackingClassifier'` labels. It should read

```python
for clf, label in zip([text_clf_bayes, text_clf_svm, sclf], 
                      ['Naive Bayes',
                       'LinearSVM',
                       'StackingClassifier']):
```

Adding the comma in should hopefully fix your problem

**Comment by rasbt** [comment]
Good catch, @jrbourbeau . I think inserting the missing comma after `'LinearSVM'` should solve the problem! Let us know in case it doesn't solve your issue, but I am pretty sure it will :)
