### ISSUE TITLE
[JOSS Review] Formatting issues in documentation

### ISSUE THREAD

**Issue by mlgill** [rasbt/mlxtend#361]
The examples section for `bootstrap_point632_score` appears to have formatting issues, [here](http://rasbt.github.io/mlxtend/api_subpackages/mlxtend.evaluate/#bootstrap_point632_score)

**Comment by mlgill** [comment]
Is is possible to improve the formatting for equations listed for metrics in [association_rules](http://rasbt.github.io/mlxtend/api_subpackages/mlxtend.frequent_patterns/#association_rules)?

**Comment by mlgill** [comment]
The examples section for `counter` appears to have formatting issues [here](http://rasbt.github.io/mlxtend/api_subpackages/mlxtend.utils/#counter).

**Comment by rasbt** [comment]
Thanks for pointing that out. The documentation is auto-generated, and I see if there's something that can be done about that via the parser. I also think the example sections are a bit redundant -- mainly a left-over back when there were no other examples in the docs.

**Comment by rasbt** [comment]
All the things you highlighted should be fixed now! I am actually never using the API docs as a reference myself but usually click on the respective user guide page and scroll down to the API section there ... 
Anyways, I just saw that the entries in the API docs were also not in alphabetical order and changed that to make it easier to navigate.
