### ISSUE TITLE
Tuning classifiers and meta-classifier

### ISSUE THREAD

**Issue by arugola** [rasbt/mlxtend#381]
I'm not sure I understand the following document in the documentation:

> However, due to the current implementation of GridSearchCV in scikit-learn, it is not possible to search over both, different classifiers and classifier parameters at the same time. 

Does that mean that classifiers (or pipe) parameters cannot be search over, in conjuction with the meta-classifier parameter?

**Comment by rasbt** [comment]
Yes, you are right. Say that the `EnsembleVoteClassifier` is the meta classifier that takes "inner" classifiers (clf1, clf2, clf3, etc.) as inputs. Currently the search is limited to either the meta-classifier parameters or the inner classifier parameters but not both at the same time. One workaround would be to e.g., write a for-loop that loops over the meta-classifier parameters and then have the GridSearch tune the inner parameters.

E.g.,

    clf_sets = [ (clf1, clf2, clf3), (clf1, clf3, clf4), ...]
    param_sets = [ param_set1, param_set2, ... ]
    for clf_set, param_set in zip(clf_sets, param_sets):
        grid = GridSearchCV(estimator=eclf, clf=clf_set, param_grid=param_set, cv=5)
        ...
