### ISSUE TITLE
Typo in User guide: Section- Exhaustive Feature Selection

### ISSUE THREAD

**Issue by hvgazula** [rasbt/mlxtend#388]
The first sentence following **Example 3 Exhaustive Feature Selection for Regression** reads as follows...

> Similar to the classification examples above, the `SequentialFeatureSelector` also supports scikit-learn's estimators for regression.

Should be `ExhaustiveFeatureSelector` instead of `SequentialFeatureSelector`

**Comment by hvgazula** [comment]
https://github.com/rasbt/mlxtend/pull/389

**Comment by rasbt** [comment]
Thanks for pointing that out. Looks like a copy&paste error, indeed!

**Comment by hvgazula** [comment]
Done.
