### ISSUE TITLE
Allowing the SequentialFeatureSelector to start with a pre-selected feature subset

### ISSUE THREAD

**Issue by Graylien** [rasbt/mlxtend#392]
First off great library!  I found it a few days ago and have already replaced huge chucks of my code with clean elegant solutions from MLXtend.  Thank you very much for making this possible and available.

I'm currently working with Sequential Feature Selection and I would like to know if it is possible, or request an enhancement if not possible, that Sequential Feature Selection allow and initial subset from which it starts with.

In my case I have 76 features and I would like to start with an Initial 20 and let forward selection go from there to save computation time, especially if float is involved.

Thanks.

**Comment by rasbt** [comment]
Thanks for the nice words and the suggestion. Seeding the SequentialFeatureSelector with a set of pre-selected features sounds like pretty useful addition, and it would be nice to add this!

Theoretically, this should be straight-forward to implement, but based on the already large code base, I want to be careful to make sure that it works as intended for both forward and backward selection. I am currently a bit busy and it would probably have to wait a little bit.

However, if you need it "right now" for you project :), and if I see that correctly, I think you can change the lines 

https://github.com/rasbt/mlxtend/blob/master/mlxtend/feature_selection/sequential_feature_selector.py#L323-L324

i.e., the lines

```python
            k_idx = ()
            k = 0
```

in 

```python
        if self.forward:
            if select_in_range:
                k_to_select = max_k
            k_idx = ()
            k = 0
```

in a copy of the code to get that to work until it's implemented.

**Comment by jorijnsmit** [comment]
This is solved in https://github.com/rasbt/mlxtend/pull/578, no?

**Comment by rasbt** [comment]
Good point. Yes, this should be addressed via the PR. Thanks for pointing that out.
