### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by Minitabb** [rasbt/mlxtend#399]
I'm new to python, so apologies if this is a silly question.

I'm trying to use mlxtend, and have installed it using pip. Pip confirms that it is installed (when I type "pip install mlxtend" it notes that the requirement is already satisfied). However, when I try and import mlxtend in python using "import mlxtend as ml", I get the error: "ModuleNotFoundError: No module named 'mlxtend'". I used the same process for installing and importing pandas and numpy, and they both worked. Any advice?

I should note that I have resorted to dropping in the specific code I need from mlxtend (apriori and association rules), which is working, but hardly a good long term strategy!

I'm using python version 2.7

Thanks!

**Comment by rasbt** [comment]
Hi there,

I suspect this could be because you have multiple python installations and the `pip` belongs to a different one? You could e.g., check which path `pip` uses by executing 

`which pip` 

on the commend line. It's weird that NumPy and Pandas work though but mlxtend doesn't.

alternatively, you could try to install the module as follows:

`python -m pip install mlxtend`

and see if that helps.

**Comment by rasbt** [comment]
I am closing this for now, please let me know if you have additional questions!

**Comment by Minitabb** [comment]
Sorry Sir, I was a little busy today so I couldn't check my email box in
the morning. I read your mail just now.
Thank you Sir. For now, I don't have any additional query. I will
definitely let you know if I got any.

**Comment by avaesyn** [comment]
Hi there, I'm wondering if you can help. Everytime I pip install mlxtend, it uninstalls panda,  numpy. Any workaround for this?

**Comment by rasbt** [comment]
Hm, that's weird, maybe you have versions that are older than those that are specified in https://github.com/rasbt/mlxtend/blob/master/requirements.txt

You could try to install it via

    pip install mlxtend --no-deps

**Comment by avaesyn** [comment]
Thanks, this seems to be working so far, will keep posted if it stops :)

**Comment by nnkundan** [comment]
for me 
"import mlxtend" is working
 but 
"mlxtend.frequent_patterns" is not working. why ?

**Comment by rasbt** [comment]
Hm, maybe you are using an old version of mlxtend? Can you do sth like

    >>> import mlxtend
    >>> print(mlxtend.__version__)  

It should ideally return 0.17.0.

**Comment by nnkundan** [comment]
"import mlxtend" .  this line is working
"print(mlxtend.__version__)"
output is 0.17.0
"from mlxtend.frequent_patterns import apriori, association_rules" but this line is not working it is showing:
File "/anaconda2/lib/python2.7/site-packages/mlxtend/frequent_patterns/apriori.py", line 191
    (iter_count, next_max_itemset), end="")
                                       ^
SyntaxError: invalid syntax

**Comment by rasbt** [comment]
It appears that you are still having the same problem with regard to using Python 2.7. Currently, mlxtend only officially/fully supports Python 3.7. 

I think you should be able to get it to work by creating a python 3.7 env if you don't want to install the Python 3 version of Anaconda. I.e., what you can do is to execute the following and then try again:

    conda create -n py37 python=3.7
    conda activate py37
    conda install mlxtend -c conda-forge

**Comment by sonalmalage09** [comment]
Has this worked for you?

**Comment by ritu13malik** [comment]
I'm new in python..
I'm trying to run an apriori ,but error occurs 
"from mlxtend.frequent_patterns import apriori, association_rules"
The above line gives me an error that,"ModuleNotFoundError: No module named 'mlxtend'"
Please guide me what should i do. I'm using python3.7.

**Comment by rasbt** [comment]
Hm, you probably didn't install mlxtend correctly then. You can either install it via

    pip install mlxtend

or 

    conda install mlxtend -c conda-forge

**Comment by JamesHallamDev** [comment]
I'm trying to use the mlxtend package. I have installed mlxtend but I am unable to import it and I am receiving the error:

ModuleNotFoundError: No module named 'mlxtend'

I have tried the ways suggested on this discussion page and my terminal is saying it is downloaded but it is still not working.

I'm using Python 3.9.2

**Comment by rasbt** [comment]
How did you install it? Based on my teaching experience, this can often happen if you have multiple versions of Python on your computer and installed it for the wrong one because conda or pip are linked to the other version.

**Comment by JamesHallamDev** [comment]
I installed it using 'pip install mlxtend'. When I check which pip is being used, it is the correct environment.

**Comment by rasbt** [comment]
Can you try installing it in the Python interpreter that couldn't import mlxtend? I.e,. via

```python
import pip
pip._internal.main(['install', 'mlxtend'])
```

**Comment by JamesHallamDev** [comment]
I'm getting a warning that pip is being invoked by an old script wrapper and then an output of '0'.

**Comment by rasbt** [comment]
I think that's normal if you call pip like that. Does the import work now though?

**Comment by JamesHallamDev** [comment]
Yes, this works great, thank you.

**Comment by rypoll** [comment]
> Yes, this works great, thank you.

Hi James, not sure how else to contact you - could you please make the repository that you forked private? This is uni work due in soon and I'm concerned it will be plagiarised. Thanks.:)

**Comment by JamesHallamDev** [comment]
Hello Ryan! Yes Ofcourse!

**Comment by rypoll** [comment]
> Hello Ryan! Yes Ofcourse!

Extremely appreciated :)

**Comment by Bibhusa4** [comment]
> I'm trying to use the mlxtend package. I have installed mlxtend but I am unable to import it and I am receiving the error:
> 
> ModuleNotFoundError: No module named 'mlxtend'
> 
> I have tried the ways suggested on this discussion page and my terminal is saying it is downloaded but it is still not working.
> 
> I'm using Python 3.9.2

have you solved it?

**Comment by Nitansh90** [comment]
Hi All!

I tried everything, but failed to install mlxtend.

Error:
Collecting mlxtend
retrying.

Pl help.

**Comment by rasbt** [comment]
How are you trying to install it?

**Comment by PooyanRezaeipour** [comment]
> your solution worked for me

your solution worked for me.
Thank you very much

**Comment by PooyanRezaeipour** [comment]
> Hm, that's weird, maybe you have versions that are older than those that are specified in https://github.com/rasbt/mlxtend/blob/master/requirements.txt
> 
> You could try to install it via
> 
> ```
> pip install mlxtend --no-deps
> ```

**Comment by PooyanRezaeipour** [comment]
> Hm, that's weird, maybe you have versions that are older than those that are specified in https://github.com/rasbt/mlxtend/blob/master/requirements.txt
> 
> You could try to install it via
> 
> ```
> pip install mlxtend --no-deps
> ```

your solution worked for me.
Thank you very much

**Comment by rasbt** [comment]
Could you try 

```python
pip install mlxtend --upgrade
```

maybe that helps
