### ISSUE TITLE
Confusion Matrix parameters in the documentation don't match actual package

### ISSUE THREAD

**Issue by bbennett36** [rasbt/mlxtend#400]
I'm trying to use the multiclass confusion matrix - http://rasbt.github.io/mlxtend/user_guide/evaluate/confusion_matrix/#example-2-multi-class-classification  
  
`cm = confusion_matrix(mds['y_test'], preds, binary=False)`  
With the above code, I'm getting the following error - `confusion_matrix() got an unexpected keyword argument 'binary'`  
  
Then I tried the other version - http://rasbt.github.io/mlxtend/user_guide/evaluate/confusion_matrix/#example-3-multi-class-to-binary  
  
`cm = confusion_matrix(mds['y_test'], preds, binary=True, positive_label=1)`  
I'm getting the same error for the binary keyword and also the 'positive_label' parameter.  
  
Then the `mlxtend.plotting.plot_confusion_matrix:` link in the page leads to a 404 error page.  
  
Is plotting the confusion matrix not supported anymore? Also, could you update the documentation so it matches the implementation?

**Comment by rasbt** [comment]
Hi there,

I just tried the confusion matrix function with the `binary` keyword argument and it worked fine for me:

```python
from mlxtend.evaluate import confusion_matrix

y_target =    [1, 1, 1, 0, 0, 2, 0, 3]
y_predicted = [1, 0, 1, 0, 0, 2, 1, 3]

cm = confusion_matrix(y_target=y_target, 
                      y_predicted=y_predicted, 
                      binary=False)
```

Have you maybe used a the binary keyword in `plot_confusion_matrix`? The `plot_confusion_matrix` is purely for visualization purposes and requires a confusion matrix created by `confusion_matrix` as input.

Thanks for pointing out the broken link, I see that there's an accidental whitespace in the link, it should be http://rasbt.github.io/mlxtend/user_guide/plotting/plot_confusion_matrix. Will fix that!

**Comment by rasbt** [comment]
Closing this for now, but please let me know if you have still issues with that function!
