### ISSUE TITLE
plot_confusion_matrix improvements

### ISSUE THREAD

**Issue by JJLWHarrison** [rasbt/mlxtend#402]
In my view, ``plot_confusion_matrix()`` could be improved if:
- There was the ability to show the coefficients of the normalised confusion matrix in addition to or instead of the absolute confusion matrix coefficients.
- The full range of the provided colormap was used (rather than the use of alpha to make the text legible)
- It was possible to show a colorbar
- The default size depended on the number of classes

I've written an extension to this function which can accomplish these things and am following the quick contributor checklist to submit for comment/review.. :)

Examples:

<img src="https://user-images.githubusercontent.com/13776395/42069903-8e8ea64e-7b97-11e8-9033-4f4179f3097c.png" width="250"/>

**Comment by rasbt** [comment]
That sounds all great points, will continue the discussion in the PR thread. Thx!

**Comment by rasbt** [comment]
This can be closed now since it's already merged. Thanks again for the PR!
