### ISSUE TITLE
What happened for using StackingCVClassifier and GridSearchCV combined

### ISSUE THREAD

**Issue by TomLin** [rasbt/mlxtend#405]
Hello,
I keep having a question in mind that I don't see any answers on google so far.

If we try to use StackingCVClassifier and GridSearchCV together to find-tune the hyper parameters,
we know the default cv for StackingCVClassifier is 2, which are already used to train the model on one set of hyper parameters from params on the training dataset.

Now again we try to use cross-validation in GridSearchCV phase. Let's say cv = 5 (as in the doc example), how can we apply 5 folds on the same training dataset? The dataset has been split into 2-folds for StackingCVClassifier. 

[example link](https://rasbt.github.io/mlxtend/user_guide/classifier/StackingCVClassifier/#example-3-stacked-cv-classification-and-gridsearch)

Thanks for any answer on my question. 
Sincerely

**Comment by rasbt** [comment]
Hi there,

> Now again we try to use cross-validation in GridSearchCV phase. Let's say cv = 5 (as in the doc example), how can we apply 5 folds on the same training dataset? The dataset has been split into 2-folds for StackingCVClassifier.

when I understand the question correctly, you are concerned about the GridSearchCV splitting the training set (already split by the StackingCVClassifier) further? Note that the order would be a bit different. It would first be split by GridSearchCV and then by the StackingCVClassifier. E.g,. if you use the StackingCVClassifier (say cv=2) and GridsearchCV (say cv=5), the iterations would look as follows:

```
for parameter setting in GridSearchCV iterator:
    for i in range(5):
        pass 4/5 of the dataset to the StackingCVClassifier
        for j in range(2):
            fit meta classifier on 1/2 of the 4/5th of the dataset (i.e, 2/5 of the orig training dataset)
```
