### ISSUE TITLE
Display warning in apriori if input DataFrame contains non-binary entries

### ISSUE THREAD

**Issue by mlagala** [rasbt/mlxtend#407]
using the apriori algorithm as follows:
`apriori(pandas_dataframe,min_support=0.01,use_colnames=False)`

I obtain:

support | itemsets
-- | --
 0.011799 | [0]
0.034455 | [1]
0.846703 | [2]
[...]
0.032113 | [0, 1, 2]

The support value is clearly wrong since support of [0,1,2] can't be higher than support of [0], and in the resultset there is no [0,1] itemset shown.

I'm using version 0.12.0

**Comment by rasbt** [comment]
Hi there,

I haven't seen anything like that before where the support of an itemset was larger than the support of it's individual items. 

I noticed that you closed the question, did you find an issue in the dataframe that lead to this result or is this still relevant -- would be happy to look into this then.

**Comment by mlagala** [comment]
Hi,
I've closed the issue since I solved the problem, which were caused by my misuse of the function.
Basically, I was using an Integer based dataframe, in which each value indecates the amount of the items, instead of an Boolean one. 
I have solved casting the dataframe with:
`df.astype(bool)`
Now it works correctly.
Thanks you

**Comment by rasbt** [comment]
Oh I see! Glad to hear that there's no bug, and thanks for the feedback!

To avoid potential issues though, I think it would be a great idea to add a check to the function that displays an error if the DataFrame values are non-binary (either non 0/1 or non True/False).
