### ISSUE TITLE
Support for sparse matrices in StackingClassifier with use_features_in_secondary=True

### ISSUE THREAD

**Issue by FlorisHoogenboom** [rasbt/mlxtend#408]
When using `StackingClassifier` with `use_features_in_secondary=True` and using a sparse matrix as input one runs into a value error on calling fit: `ValueError: all the input arrays must have same number of dimensions`. This seems caused by the fact that the results of the meta estimator cannot be concatenated to the sparse matrix.

Would you consider adding support for sparse matrices with `use_features_in_secondary` set to True? If so, I would be happy to open a PR for this!

**Comment by rasbt** [comment]
Thanks for the note! Having support for thios would be awesome, and I would appreciate a PR!

I think this might also affect the StackingCVClassifier, StackingRegressor, and StackingCVRegressor. However, we can tackle them one by one, and starting with the StackingClassifier would be great

**Comment by FlorisHoogenboom** [comment]
You are probably right, I believe the logic for merging the meta estimator output and the original feature matrix is the same for all of those. I hope to have some time next week to have a look at those as well and will submit a PR for those seperately.

**Comment by FlorisHoogenboom** [comment]
Awesome!
