### ISSUE TITLE
Get Stacking.... has no attribute classes_

### ISSUE THREAD

**Issue by mbhatt1** [rasbt/mlxtend#423]
I get the following error ```AttributeError: 'StackingClassifier' object has no attribute 'classes_'``` Sklearn version 0.19.2. Fix is rollback to a previous version in my case. Api mismatch?

**Comment by mbhatt1** [comment]
Just kidding. Its still not working. Should I be putting in something else instead of logistic regression for metaclassifier for classification process?

**Comment by rasbt** [comment]
Hi there,

Logistic regression from scikit-learn should work just fine, I am using it in most of the examples in the StackingClassifier documentation.

Could you maybe add a code snippet example that reproduces that error? Would be happy to look into it. But ss far as I remember, the StackingClassifier never had a `classes_` attribute. Are you trying to access it manually, or is that something that occurs if you are using some other function that takes in a StackingClassifier (like grid search or so).

**Comment by mbhatt1** [comment]
Oh ok, Thank you!
