### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mbhatt1** [rasbt/mlxtend#426]
Trying to use this as the local node classifier together with the hierarchical classifier API from 
```
https://github.com/globality-corp/sklearn-hierarchical-classification. 
```
If I use the StackingClassifier class it keeps telling me that
```
'StackingClassifier' object has no attribute 'classes_'
```
if I use the StackingCVClassifier then it keeps telling me that
```
TypeError: only integer scalar arrays can be converted to a scalar index
Please check that X and yare NumPy arrays. If X and y are lists of lists,
try passing them as numpy.array(X) and numpy.array(y).
```
I did pass arrays into the classifier and not dataframes. Could someone help me please?

**Comment by rasbt** [comment]
Hi there,

> 'StackingClassifier' object has no attribute 'classes_'

I am not familiar with the `sklearn-hierarchical-classification` package, but if it requires `classes_` attribute, it would be no problem to add one (similar to e.g. the RandomForestClassifier in scikit-learn).

> TypeError: only integer scalar arrays can be converted to a scalar index

Hard to tell what's going on in this case. I think the unit tests cover both numpy arrays and DataFrames, so there shouldn't be an issue in general. Can you share a code snippet to reproduce that issue for further debugging? Or if that's not possible, maybe share the output of
 
    >>> print(type(X))
    >>> print(X.shape) # if it's an array

(and the same for `y`)

**Comment by mbhatt1** [comment]
HI there, 

X is a dataframe but when I create a classifier, I pass in X.values. X.shape would be (14000,11) there are 11 features which I am using. 

Could you elaborate more on what you mean by adding the classes_  attribute? 

```
    stack_hierarchical = StackingClassifier(classifiers=[mlp_classifier, clf1, GaussianNB(), svm_classifier], meta_classifier=lr, use_probas=True)
    base_estimator = make_pipeline(
        #TruncatedSVD(n_components=11),
        #CountVectorizer(),
#	DenseTransformer(),
#	FunctionTransformer(lambda x: x.todense(), accept_sparse=True), 
	stack_hierarchical
    )
    hierarchicalclf = HierarchicalClassifier(
        base_estimator=base_estimator,
        class_hierarchy=class_hierarchy,
    )
```
is how I set it up

```
	y_pred= cross_val_predict(clf, X.values, y.values , n_jobs=-1, cv=10)
    	cfn_matrix = confusion_matrix(y, y_pred)
```
is how I have it make a prediction and calculate the results. Moreover, the class labels for y are text. the data looks like this

[11 dimensional features] [12th position has a string label]

Just using stacking with k-NN, GaussianNB() and svm in the base layer and lr in the meta layer works just fine! Therefore I am confused. 

Manish

**Comment by rasbt** [comment]
> X is a dataframe but when I create a classifier, I pass in X.values. X.shape would be (14000,11) there are 11 features.

Have you used the same data type during training and testing? Otherwise this could explain the problem. I.e. if you trained on the DataFrame and then test on an array, this may cause issues. 

could you try

a) using an numpy array for both training and evaluation

and/or

b) using a dataframe for both training and evaluation


> Could you elaborate more on what you mean by adding the classes_ attribute?

from the RandomForestClassifier documentation at http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

> classes_ : array of shape = [n_classes] or a list of such arrays
The classes labels (single output problem), or a list of arrays of class labels (multi-output problem).

**Comment by mbhatt1** [comment]
Well I use the crossvalpredict function so I am assuming its gonna be array if I pass it along as an array?

**Comment by rasbt** [comment]
So the error occurs during cross_val_predict? That's weird, because it does it's own training and fitting based on what input data you provide. Also it works fine for me if I run a simple example

```python
from sklearn import datasets
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from mlxtend.classifier import StackingCVClassifier
import numpy as np


iris = datasets.load_iris()
X, y = iris.data, iris.target


clf1 = KNeighborsClassifier(n_neighbors=1)
clf2 = RandomForestClassifier()
clf3 = GaussianNB()
lr = LogisticRegression()
sclf = StackingCVClassifier(classifiers=[clf1, clf2, clf3], 
                            meta_classifier=lr)

cross_val_predict(sclf, X, y)
```

Reading your previous comment again I stumbled upon the following:

> Moreover, the class labels for y are text

This could explain the issue though, class labels should be integers (I think floats are also fine)

**Comment by mbhatt1** [comment]
See, if I run it by not using hierarchical classification, it runs fine for y as text. I mean if I just use stacking classifier with no hierarchical classification then I have no error. It provides me with an accuracy. Is that correct? 

```
    for clf, label in zip([GaussianNB(), clf1, svm_classifier, stack, stack_svm, stack_gaussian, hierarchicalclf], ['Gaussian' , 'k-NN', 'SVM', 'Stacking', 'Stacking_SVM', 'Stacking_Gaussian', 'hierarchical']):
	y_pred= cross_val_predict(clf, X.values, y.values , n_jobs=-1, cv=10)
    	cfn_matrix = confusion_matrix(y, y_pred)
	file_handle.write('Classifier Name: '+ label+'\n\n\n')
    	file_handle.write ('Confusion\n' + str(cfn_matrix)+'\n')
    	file_handle.write( 'Classification Report:\n'+ str(classification_report(y, y_pred))+'\n')

```
This is my loop. It executes everything till it hits hierarchical. And then it shows the error that I mentioned in my first comment.

**Comment by mbhatt1** [comment]
Oh I appreciate your time :)

**Comment by rasbt** [comment]
> See, if I run it by not using hierarchical classification, it runs fine for y as text.

Oh I see, I never pass text to classifiers directly and hence haven't tested that scenario before. However, it's good to know that it works (prob. because i am using the LabelEncoder internally in the Stacking(CV)Classifier). 

> This is my loop. It executes everything till it hits hierarchical.

I don't know how the hierarchical API works and it could be that it passes some non-array format to the classifiers although you give it numpy arrays? I.e. you provide a numpy array to the cross_val_predict function, which splits it into training and test folds, and then sth within that "hierarchical" functionality converts it to sth else?

So it's maybe an issue with the HierachicalClassifier rather than with the StackingClassifier?

**Comment by mbhatt1** [comment]
Maybe! I have an issue posted there too. I just wanted to make sure I'm not making things up in my head. 

But theres another thing too. I can pass in stuff just using the hierarchical classifier without stacking and it works. Idk maybe its the issue of classes_. I see you have the classes_ attribute in the ensemble_voting file. Are the changes to be made in the same places? I can try that!

**Comment by rasbt** [comment]
I see. Hm, that's strange. Would be nice if it's just due to the `classes_` attribute :). Yes, the changes to StackingClassifier and StackingCVClassifier should in principal be the same as the ones already made in the EnsembleVoteClassifier

**Comment by mbhatt1** [comment]
Thank you professor! Thank you for your prompt replies too. I appreciate it.

**Comment by mbhatt1** [comment]
Also if you are looking for PhD students, please let me know haha :)

**Comment by mbhatt1** [comment]
Hello Professor, 

I am checking if the changes I made inside the fit function are correct: 

![image](https://user-images.githubusercontent.com/5893997/43690862-345692ba-98d7-11e8-8db2-36c3e63851e7.png)

**Comment by rasbt** [comment]
At first glance this looks okay to me. Maybe consider submitting this as a PR, which would have to benefits: it's easier to see the diff (the modifications you made), and it would be a useful addition to the library :)

**Comment by mbhatt1** [comment]
Ok
