### ISSUE TITLE
Support for `sample_weight` in the `fit` method

### ISSUE THREAD

**Issue by kota7** [rasbt/mlxtend#438]
Is there any plan or demand for supporting `sample_weight` option in the `fit` method of estimators?  

Since a number of model classes in scikit-learn support it, I suppose it would be useful for estimators such as `StackingRegressor` (provided that all regressors accept it).

I saw a related PR #255 about the support for `fit_params` options.  Once this is merged, `sample_weight` will be implementable by passing same weights to all regressors and meta-regressor.  Even so, API like `fit(X, y [, sample_weight])` can be handy.

**Comment by rasbt** [comment]
I think support for `sample_weight` would be a good thing to have. I think if the fit methods support `fit_params` the `sample_weight` would be supported automatically, right? I am currently not sure whether #255 is still active. If not, would you like to take it over?

**Comment by kota7** [comment]
@rasbt I will have a look.  At first glance, it looks close but not entirely automatic.  In #255 it looks `fit_params` are given per estimator basis, while support for `sample_weight` requires options applied to all estimators in the both levels.

**Comment by rasbt** [comment]
Good point. Maybe having a separate `sample_weights` param would be the better option then.
