### ISSUE TITLE
Iris dataset UCI Machine Learning Repo Note

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#447]
Add a note that two data points in UCI's Machine Learning repo are different from the Iris dataset in R (and the one in the original Fischer paper)

**Comment by janismdhanbad** [comment]
Hi, I am a beginner in contributing, I have identified that row number 34 and 37 are different in UCI repo data and the dataset in R. The required note should go [here](http://rasbt.github.io/mlxtend/user_guide/data/iris_data/#iris-dataset), right? I have attached a screenshot for reference.

![image](https://user-images.githubusercontent.com/15145740/57581859-6a348f00-74db-11e9-87ae-cd58f267d6cc.png)

**Comment by rasbt** [comment]
Thanks for looking into this! I think the best place for adding a node would be in the docstring. The section under "API" in the documentation that you linked above is generated automatically from the function docstring, so by adding that there, we have the advantage of having this note in both places then. (Compared to adding it just to the documentation).

I am just thinking that we could actually have both versions of the dataset -- it may be useful to people who want to directly compare some Python and R functions. I.e. the `iris_data()` function would get a new parameter:

- `iris_data(version='uci')` (default)
- and `iris_data(version='R')`

Inside the `iris_data` function, we can add an 

    if version == 'R':
        # replace values in line 34 and 37

**Comment by janismdhanbad** [comment]
@rasbt  Okay, I am looking into this.
