### ISSUE TITLE
Question: feature selection for gaussian processes with anisotropic kernels

### ISSUE THREAD

**Issue by matteoaldeghi** [rasbt/mlxtend#454]
I wonder whether it is possible to use `SequentialFeatureSelector` with  anisotropic kernels in `GaussianProcessRegressor`. I understand it may be more of an issue with how this is specified in scikit-learn rather than a limitation of mlxtend, but being fairly new to both packages I may be overlooking an easy way around this?

**Comment by rasbt** [comment]
Good question. GP are one of the few classes within sklearn that I haven't used actually. I assume that if you set the random seed before each experiment, then the results should be deterministic. So I suppose it is somewhat fair to compare different configurations this way. An issue though is that RBF kernels are typically very sensitive the the kernel width / hyperparameters of the kernel. So if you use one setting that is maybe good for one feature subset, it may not be good for another.

Maybe one workaround would be to run the feature selection with different hyperparam, and then pool the results for each evaluated feature set. E.g., if you have a fitting score for feature subset (2, 3,  5) for 5 different hyperparam values, I would take the best one. 

It's still not ideal though and SFS is a greedy procedure after all. If you can afford it computationally, if your feature set is relatively small, also consider the exhaustive feature selector maybe.

**Comment by matteoaldeghi** [comment]
Thanks for the quick response! I realised I did not phrase the question clearly, and we may be referring to slightly different problems. 

What I was thinking of is the fact that for some kernels (e.g. RBF and Matern) scikit-learn also implements a variant where one can specify a different kernel width for each feature:
http://scikit-learn.org/stable/modules/gaussian_process.html#radial-basis-function-rbf-kernel

When doing this, the hyperparameter `length_scale` is an array of length `n_features`. But since the number of features changes during the selection procedure, scikit-learn raises an error because the shape of the hyperparameter is not compatible with that of the training data (number of columns != length of `length_scale` hyperparameter). 

To give an example for a hypothetical regression with 3 features:
```python
# define gp with shape(length_scale) = (n_features,)
kernel = RBF(length_scale=[1.0, 1.5, 0.5])
gpr = GaussianProcessRegressor(kernel)

# define kfold split
kfold = KFold(random_state=42)

# feature selection
select = SFS(gpr, cv=kfold, k_features="best")

# shape(X) = (n_samples, n_features)
# shape(Y) = (n_samples, )
select.fit(X,Y)
```

The above code would fail with scikit-learn raising the following error:
```python
ValueError: Anisotropic kernel must have the same number of dimensions as data (3!=1)
```
 
So, although I encountered this only with GPs so far, I guess my question may be phrased more generally (and possibly more accurately) as: is there a way to use the feature selection classes with models in which the shape of some hyperparameter depends on the number of features used for training, given this will change during the feature selection procedure?

**Comment by rasbt** [comment]
Oh I see! I think this is more a technical rather than a conceptual problem then, and I think it could be solved more easily :).

I think the following might work:

1) You could create a "meta estimator" (basically a class based on BaseEstimator, e.g., like https://github.com/rasbt/mlxtend/blob/master/mlxtend/preprocessing/copy_transformer.py, that has rudimentary `fit`, `predict`, `predict_proba` methods etc.)

2) In the `fit` method of this meta estimator, you would instantiate a new gaussian process estimator with the desired kernel dim derived from the current dataset. 

E.g., something like this (this is just an example):

```python

class YourMetaEstimator(BaseEstimator):

def __init__(self, params, ...):
    self.params = params
    ...

def fit(self, X, y):

    kernel = RBF(length_scale=[1./X.shape[1] for i in range(X.shape[1])])
    self.model = GaussianProcessRegressor(kernel, self.params)
    self.model.fit(X, y)

def predict(self, X, y):
    self.model.predict(X, y)
```

**Comment by matteoaldeghi** [comment]
Ah! Seems like a good/easy workaround indeed. Thanks!
