### ISSUE TITLE
SequentialFeatureSelection keeps hanging on the same point

### ISSUE THREAD

**Issue by bcoghe** [rasbt/mlxtend#467]
Hi guys,

I've implemented the SFS in the following way:

```
print 'nr_features: {0}'.format(nr_features)
clf = svm.SVC(C=10,gamma='scale',kernel='linear')
selector = SFS(clf, 
           k_features=nr_features,
           forward=True, 
           floating=False, 
           verbose=2,
           scoring='accuracy',
           n_jobs = 2)
selector = selector.fit(data, dose_error_flags)
print selector
print selector.subsets_
print selector.k_feature_idx_
print selector.k_score_
```

It starts running and somewhere in the 3rd feature selection loop it just hangs. It doesn't print any logs anymore. Furthermore, the cpu utilization is not dropping but still going strong. I'm using ubuntu on windows bash with python2.7

Logs below:

![image](https://user-images.githubusercontent.com/15378385/48713886-b5977000-ec11-11e8-87d4-bfaf32f5968d.png)

**Comment by rasbt** [comment]
I think this has been a Python multiprocessing issue on Windows, which cannot be fixed within mlxtend itself. Please reopen if this needs further investigation.
