### ISSUE TITLE
Decision Regions : Classifier trained on more than two features

### ISSUE THREAD

**Issue by AlphaRandom** [rasbt/mlxtend#472]
Hi, I noticed  anytime you pass on a classifier trained on more than two features to the decision_regions function, you'll only get 3 classes (Dataset is 8 features and 4 classes). We also know that in this case we have to use both filler_feature_values and filler_feature_ranges and also feature_index to plot the regions. Result always shows only 3 decision regions, while if I pass same classifier only trained on two features I can see four regions as expected. Thanks

**Comment by rasbt** [comment]
Hi,

I am not sure how many feature filler values you have tried, but my guess is that the decision region of for one of the classes is just not present at that slice. I don't think there is a technical issue and just ran this on one of the examples by increasing it to 4 classes. 

I suggest that you try out different filler feature values.


```python
from mlxtend.plotting import plot_decision_regions
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.svm import SVC

# Loading some example data
X, y = datasets.make_blobs(n_samples=500, n_features=3, centers=[[2, 2, -2],[-2, -2, 2], [-2, -2, -2], [2, 2, 2]],
                           cluster_std=[2, 2, 2, 2], random_state=2)

# Training a classifier
svm = SVC(gamma='auto')
svm.fit(X, y)

# Plotting decision regions
fig, axarr = plt.subplots(2, 2, figsize=(10,8), sharex=True, sharey=True)
values = [-4.0, -1.0, 1.0, 4.0]
width = 0.75
for value, ax in zip(values, axarr.flat):
    plot_decision_regions(X, y, clf=svm,
                          filler_feature_values={2: value},
                          filler_feature_ranges={2: width},
                          legend=2, ax=ax)
    ax.set_xlabel('Feature 1')
    ax.set_ylabel('Feature 2')
    ax.set_title('Feature 3 = {}'.format(value))

# Adding axes annotations
fig.suptitle('SVM on make_blobs')
plt.tight_layout()
plt.show()
```

![unknown-1](https://user-images.githubusercontent.com/5618407/49025857-24208480-f162-11e8-8d08-61796751a1c1.png)

**Comment by AlphaRandom** [comment]
Well, I am giving a try. I suspect you are right. Anyway I used  for all remaining features (six) their average as filler_feature_value and their standard deviation as fille_feature_range. At the moment I am plotting by considering a classifier trained on two features and I can see all four regions. Point is that I originally trained my classifier on all 8 features that's why I would like to see the decision regions based on all features and it seems like that  using those values (average,standard deviation) I always see only three regions. What alternative values could I use ?

**Comment by kurikabocya** [comment]
X, y = datasets.make_blobs(n_samples=500, n_features=3, centers=[[2, 2, -2],[-2, -2, 2], [-2, -2, -2], [2, 2, 2]],
                           cluster_std=[2, 2, 2, 2], random_state=2)

Hellow, teach me the meaning of [2,2,-2]'s last -2,  [-2, -2, 2]'s last 2,,

I understand [2,2,-2]'s first [2,2] is center location, [-2, -2, 2]'s first [-2,-2] is center location
