### ISSUE TITLE
TyprError: Unhashable type: 'slice;

### ISSUE THREAD

**Issue by Thek10patil** [rasbt/mlxtend#486]
I am trying to run SFS, SFFS, SBS, SFBS one after another on the same dataset. I am able to get the result from SFS but after that when SFFS start to run it gives an error unhashable slice error. I think this is related to some cache problem. It is storing some values. 

-----------------------------------------------------------------------------------------------------------

```python
from mlxtend.feature_selection import SequentialFeatureSelector as sfs
# Build RF classifier to use in feature selection
clf = RandomForestClassifier(n_estimators=100, n_jobs=-1)

# Build step forward feature selection
sfs1 = sfs(clf,
           k_features=5,
           forward=True,
           floating=False,
           verbose=2,
           scoring='accuracy',
           cv=5
          )

# Perform SFFS
sfs1 = sfs1.fit(x_Unit_Level_Parameter_df, y_Unit_Level_Parameter_df)
print("-----------------------------------------------------------------------------------------------------")
print(sfs1.subsets_)
print("-----------------------------------------------------------------------------------------------------")
print("Score using SFFS with Random Forest Classifier",sfs1.k_score_)
print("-----------------------------------------------------------------------------------------------------")
print("******Important Features using SFS are*******")
print(sfs1 .subsets_['feature_names']


-------------------------------------------------------------------------------------------------------------------
**************************************************************************************************************

______________________________________________________________________________________________________________

from sklearn.ensemble import RandomForestClassifier
from mlxtend.feature_selection import SequentialFeatureSelector as sfs
randomClf = RandomForestClassifier(n_estimators=100)

# Build step forward feature selection
sbs = sfs(randomClf,
           k_features=5,
           forward=False,
           floating=False,
           verbose=2,
           scoring='accuracy',
           cv=5
          )

# Perform SFFS
sbs = sbs.fit(x_Unit_Level_Parameter_df, y_Unit_Level_Parameter_df)
print("-----------------------------------------------------------------------------------------------------")
print(sbs.subsets_)
print("-----------------------------------------------------------------------------------------------------")
print("Score using SBFS with Random Forest Classifier",sbs.k_score_)
print("-----------------------------------------------------------------------------------------------------")
print("******Important Features using SBFS are*******")
print(sbs.subsets_['feature_names'])
```

**Comment by rasbt** [comment]
Hi,

the SFS doesn't do any caching itself. Maybe it's something related to the pandas DataFrames. Could you provide the complete error message? It would be helpful for finding out where exactly the error occurs.

**Comment by Thek10patil** [comment]
Hi Sebastian,

I changed dataframe into numpy ndarray and it is working very good now. 

Thank you so much for the quick response. 

I have one doubt and I need advice on that. Data on which I am working is class/label imbalanced. So which method should I go for feature selection? And which classifier I should use?

Data imbalance information:

Label 0 ---> 2,73,000 rows
Label 1 ---> 1890 rows

**There are 13 features and I want to know which features are important.**  So I am using SFS, SBS, SFFS, SBFS along with XGboost and Select from model.  After that, I am going to take common important features from the above methods.

Before applying feature selection methods are there any conditions on data?
 1. Like data should be balanced
 2. Which classifier should use?

**Comment by Thek10patil** [comment]
Thank you. My assumption is that my sequence should be like

Preprocessing(handling NAN values)
SMOTE
Feature Selection Algorithms
Feature_importance_permutation
Different ML Models

**Right?**

**Comment by rasbt** [comment]
That sounds like a good plan. Instead of doing the steps Feature Selection Algorithms & Feature_importance_permutation sequentially, I would also consider doing them in parallel within the order you proposed. I.e., 

Preprocessing(handling NAN values)
SMOTE
Feature Selection Algorithms
Different ML Models

and

Preprocessing(handling NAN values)
SMOTE
Feature_importance_permutation
Different ML Models

Regarding this issue, is it okay to close it or do you think there is a DataFrame issue that is still unresolved?
