### ISSUE TITLE
StackingCVClassifier: How do you get predictions for new test?

### ISSUE THREAD

**Issue by Jie-Yuan** [rasbt/mlxtend#489]
How do you get predictions for new test?

Shouldn’t it be test_skf_mean????

**Comment by Jie-Yuan** [comment]
![Uploading image.png…]()
How do you get predictions for new test?
Shouldn’t it be test_avg????

**Comment by rasbt** [comment]
Could you please let me know which code file in mlxtend this is, or is this something in the mlxtend documentation?

**Comment by Jie-Yuan** [comment]
This is achieved by other people in kaggle.

**Comment by Jie-Yuan** [comment]
class Ensemble(object):
    def __init__(self, n_folds, stacker, base_models):
        self.n_folds = n_folds
        self.stacker = stacker
        self.base_models = base_models

    def fit_predict(self, X, y, T):
        X = np.array(X)
        y = np.array(y)
        T = np.array(T)

        folds = list(KFold(n_splits=self.n_folds, shuffle=True, random_state=2016).split(X))

        S_train = np.zeros((X.shape[0], len(self.base_models)))
        S_test = np.zeros((T.shape[0], len(self.base_models)))

        for i, clf in enumerate(self.base_models):
            S_test_i = np.zeros((T.shape[0], len(folds)))

            for j, (train_idx, test_idx) in enumerate(folds):
                X_train = X[train_idx]
                y_train = y[train_idx]
                X_holdout = X[test_idx]
                # y_holdout = y[test_idx]
                clf.fit(X_train, y_train)
                y_pred = clf.predict(X_holdout)[:]
                S_train[test_idx, i] = y_pred
                S_test_i[:, j] = clf.predict(T)[:]

            S_test[:, i] = S_test_i.mean(1)

        self.stacker.fit(S_train, y)
        y_pred = self.stacker.predict(S_test)[:]
        return y_pred

**Comment by Jie-Yuan** [comment]
I think new -test -predictions should be `S_test[:, i] = S_test_i.mean(1)`

**Comment by Jie-Yuan** [comment]
`No similar implementations found in your code`

**Comment by rasbt** [comment]
> I think new -test -predictions should be S_test[:, i] = S_test_i.mean(1)

I think that might be right, but I think there are other issues in the code. In Stacking, you want to use the holdout predictions for fitting the meta classifier to avoid overfitting etc. 

Please no offense, but I am closing this, because this issue tracker is primarily for discussing mlxtend-related code. For general questions about the Kaggle code it might be better to ask them on the Kaggle forum or StackOverflow.

**Comment by Jie-Yuan** [comment]
No similar implementations found in mlxtend code

**Comment by Jie-Yuan** [comment]
![image](https://user-images.githubusercontent.com/20265321/50747779-bbecb480-1270-11e9-961d-cfd9f12b8a63.png)

cv = 5
Get meta-features of test-data:
The above picture is 5 base-models avg, but mlxtend is  5th base-model

**Comment by rasbt** [comment]
I don't think the averaging makes sense in the figure, because all Model 1's are the same?

In mlxtend, there is now averaging, instead, the meta classifier uses all the features from stacking the predictions of the first level classifiers

**Comment by Jie-Yuan** [comment]
base-model is  trained through different data, thus, This way you can get 5 models.

**Comment by Jie-Yuan** [comment]
> In mlxtend, there is no averaging, instead, the meta classifier uses all the features from stacking the predictions of the first level classifiers

cv = 5
all the features from stacking the predictions of the first level classifiers has `num_classifiers * 5 *` columns? In addition to the average, how to stack?

**Comment by rasbt** [comment]
As mentioned in the docstring, the metafeatures have shape `shape = [n_samples, n_classifiers]`. 
Let's say your dataset has 100 training examples. Then with cv=5, there are 5 test folds with size 20. These test folds are then stacked for each classifier (say you have 3 level0 classifiers) to yield a 100x3 matrix.

**Comment by rasbt** [comment]
Maybe it's more clear if you look at the algorithm, which is easier to read than the code:

![stacking_cv_algorithm](https://user-images.githubusercontent.com/5618407/50750675-a2655180-120b-11e9-9fad-723b17b26247.png)

The stacking occurs in line 10. This algorithm is for training. The testing would then look as follows:

![stacking_cv_algorithm](https://user-images.githubusercontent.com/5618407/50750733-f07a5500-120b-11e9-873a-b62fbe4aec1c.png)

Hope this makes it more clear. Why we are stacking and no averaging should be used.

**Comment by Jie-Yuan** [comment]
Thanks!
