### ISSUE TITLE
TransactionEncoder() resulted in fewer columns then items in data

### ISSUE THREAD

**Issue by gowestyang** [rasbt/mlxtend#494]
My transaction data contains 980 unique items.
However, the encoded result of TransactionEncoder() contains only 704 columns.
I examed the "filtered" items (which are not presented as columns), but I couldn't identify any pattern to tell me why TransactionEncoder() did not include them.

Add:
The same columns are missing if I use sklearn.preprocessing.MultiLabelBinarizer.
However, pd.get_dummies() will reserve all my columns.

**Comment by rasbt** [comment]
Hi there,

just following up on this ... since you closed this issue, is this issue resolved or is there an issue with the TransactionEncoder() that might be looked into? The transaction encoder should not exclude certain columns.

**Comment by gowestyang** [comment]
> Hi there,
> 
> just following up on this ... since you closed this issue, is this issue resolved or is there an issue with the TransactionEncoder() that might be looked into? The transaction encoder should not exclude certain columns.

It was my own mistake. My raw data is a long table and I need to transfer it to transaction table (series of list) through grouping by "users" and "sectors". My "sectors" contains missing value which caused the problem.

On the other hand, when I use pd.get_dummies(), I did encoding before grouping by so there was no missing column.
