### ISSUE TITLE
a problem about StackingCVClassifier

### ISSUE THREAD

**Issue by FontTian** [rasbt/mlxtend#520]
this code in StackingCVClassifier.fit()

```
        # Fit the base models correctly this time using ALL the training set
        for model in self.clfs_:
            if sample_weight is None:
                model.fit(X, y)
            else:
                model.fit(X, y, sample_weight=sample_weight)
```

This will affect GridSearchCV.best_params_ ???

**Comment by rasbt** [comment]
Sorry for the late response, somehow overlooked this. No, this shouldn't affect the GridSearchCV params as they are hyperparams. It's just fitting the models to the training data but will not change hyperparameters.

**Comment by FontTian** [comment]
Thank you
