### ISSUE TITLE
Drop last proba column in StackingClassifier and StackingCVClassifier

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#527]
Due to the linear dependence, I think it makes sense to drop one of the probability columns in StackingClassifier etc. if `use_probas=True`. I.e., 

```python
        if self.use_probas:
            probas = np.asarray([clf.predict_proba(X)
                                 for clf in self.clfs_])
```

could be changed to

```python
        if self.use_probas:
            if self.drop_last_proba:
                probas = np.asarray([clf.predict_proba(X)[:, :-1]
                                     for clf in self.clfs_])
            else:
                probas = np.asarray([clf.predict_proba(X)
                                     for clf in self.clfs_])
```

**Comment by bmreiniger** [comment]
As in https://github.com/rasbt/mlxtend/issues/185 , I think it would be nicer to be able to choose which probability column to drop.  In particular, in a binary problem usually we would prefer to drop the first one since the second column is the probability of the "positive" class.

**Comment by rasbt** [comment]
Yeah, we could extend that to support that. I will open a separate issue for that to have it on the radar. And I would welcome a PR for this :)
