### ISSUE TITLE
unit tests - actual and expected parameters transposed in several tests

### ISSUE THREAD

**Issue by arc12** [rasbt/mlxtend#536]
observed in test_sequential_feature_selector.py:

e.g. in test_knn_wo_cv
param order passed to dict_compare_utility is expect, actual
these are passed forward to numpy utility, where the order is actual, expect

appears to be the case in several tests.

**Comment by rasbt** [comment]
Thanks for bringing this up. This should be fixed of course. However, it wouldn't really make a difference since it is just checking whether two dictionaries are the same?
