### ISSUE TITLE
Install mlxtend via conda create

### ISSUE THREAD

**Issue by qiagu** [rasbt/mlxtend#538]
I tried command like
`conda create --name newenv python=3.6 mlxtend=0.16.0`. 
It returned
```
PackagesNotFoundError: The following packages are not available from current channels
```
@rasbt  Can we make `mlxtend` support conda installation?

**Comment by rasbt** [comment]
> @rasbt Can we make mlxtend support conda installation?

I am not sure if it is possible, that depends on the conda maintainers. However, it should be in conda-forge / you can install it from the conda-forge channel. 

    conda install mlxtend --channel conda-forge

**Comment by qiagu** [comment]
wow, the `conda-forge` channel works. Thanks @rasbt
