### ISSUE TITLE
plot decision regions zoom

### ISSUE THREAD

**Issue by Sindreedelange** [rasbt/mlxtend#541]
Hi, I was wondering if there is any way to zoom out of a plot, rendered by the `plot_decision_regions`-function? More specifically, I have plotted a SVM model, using a RBF kernel, on the Iris dataset (using only class 0 and 1):
![image](https://user-images.githubusercontent.com/9415625/58162790-1d8f4780-7c83-11e9-8971-eeea25173559.png)
I would like the plot to be zoomed out, such that one can clearly see the circle that the RBF kernel makes, if possible.

**Comment by rasbt** [comment]
Good point. Currently, this is not possible and would require tweaking the lines

https://github.com/rasbt/mlxtend/blob/master/mlxtend/plotting/decision_regions.py#L203

```python
    # Get minimum and maximum
    x_min, x_max = X[:, x_index].min() - 1, X[:, x_index].max() + 1
    if dim == 1:
        y_min, y_max = -1, 1
    else:
        y_min, y_max = X[:, y_index].min() - 1, X[:, y_index].max() + 1

    xnum, ynum = plt.gcf().dpi * plt.gcf().get_size_inches()
    xnum, ynum = floor(xnum), ceil(ynum)
    xx, yy = np.meshgrid(np.linspace(x_min, x_max, num=xnum),
                         np.linspace(y_min, y_max, num=ynum))
```

I.e., 


the -1 and +1 in

    x_min, x_max = X[:, x_index].min() - 1, X[:, x_index].max() + 1
    y_min, y_max = X[:, y_index].min() - 1, X[:, y_index].max() + 1

could be replaced by a custom zoom factor.

I.e., we could add a `zoom_factor` argument to the function, and then compute it as

    x_min, x_max = X[:, x_index].min() - 1/zoom_factor, X[:, x_index].max() + 1/zoom_factor

**Comment by Sindreedelange** [comment]
I only needed it for visualization purposes, so I set the `gamma` parameter to 1.8 - but it would've been a great addition to the software :)
