### ISSUE TITLE
No module named colorama...

### ISSUE THREAD

**Issue by Jcorban1890** [rasbt/mlxtend#542]
So, Ive been trying to run this file for quite some time, I have gotten a ton of help, but none seem to work. When i drag the openme.py file into a command prompt file and enter, it says no module named colorama. After tryiny to install colorama with various commands, unistalling it, reinstalling it all multiple times, nothing has worked. Even weirder, when i try to use the command pip install colorama, it says i have it, but when i run the file after it says i dont have it. Any help would be appreciated.  ![image](https://user-images.githubusercontent.com/42871935/58387286-e8ac2900-7fd1-11e9-9dbd-e395715a80c2.png)

**Comment by rasbt** [comment]
There is no colorama library being used in mlxtend, I think you got the wrong repository?
