### ISSUE TITLE
figsize in plot_sequential_feature_selection

### ISSUE THREAD

**Issue by kazyka** [rasbt/mlxtend#554]
Is it by any means possible to increase the figsize when using

```
from mlxtend.plotting import plot_sequential_feature_selection as plot_sfs

plot_sfs(sfs1.get_metric_dict(), kind='std_dev')
```

whatever I do, I can only manage to create an emtpy new figure, whereas the plot from `plot_sfs` is above the empty larger figure

**Comment by rasbt** [comment]
Ah good point. There should be a `figsize` parameter added, which could then be passed to the plt.figure call here: https://github.com/rasbt/mlxtend/blob/master/mlxtend/plotting/plot_sequential_feature_selection.py#L58

similar to how it's done in https://github.com/rasbt/mlxtend/blob/master/mlxtend/plotting/plot_sequential_feature_selection.py#L58

**Comment by kazyka** [comment]
Added via #555
