### ISSUE TITLE
Adaline User Guide Figures Mislabeled

### ISSUE THREAD

**Issue by filipj8** [rasbt/mlxtend#556]
The `plot_decision_regions` figures in the User Guide for Adaptive Linear Neuron -- Adaline `/mlxtend/docs/sources/user_guide/classifier/Adaline.ipynb` have the incorrect titles for examples 1, 2, and 4. Currently all the titles are 'Adaline - Stochastic Gradient Descent', which corresponds to example 3.

**Comment by rasbt** [comment]
Good catch, and thanks for the note! Just fixed that in the Jupyter notebooks, and it will be reflected in the HTML docs upon the next version release.
