### ISSUE TITLE
Documentation - Incorrect Code

### ISSUE THREAD

**Issue by kyle-pena-nlp** [rasbt/mlxtend#560]
On the page http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/apriori/#references, Example 3, line 2 should us "oht_ary" instead of te_ary

**Comment by rasbt** [comment]
Thanks for the note! Either would work but `oht_ary` would be better here. Just added a PL for the fix -- will merge after the unit tests complete. The online (website) version will then automatically be updated upon the next version release.
