### ISSUE TITLE
Can SFS return the metric score of test set and train set individuallly?

### ISSUE THREAD

**Issue by werhoog** [rasbt/mlxtend#564]
Hey, thanks for this software! As I know, when split data into train set and test set in cross validation, there are metric scores(like R2) in test set and train set, but  I only find one score return(not scores in test set or train set) using SFS. So can  SFS return scores for both test set and train set in cross validation. Thanks !!!

**Comment by rasbt** [comment]
Glad to hear that you find it generally useful. You are right, currently only those scores from the test folds are saved. Training scores are not saved and hence not returned. If you want to return the training scores, you would have to customize the code to your needs.
