### ISSUE TITLE
Possibly incorrect info in documentation

### ISSUE THREAD

**Issue by pedro-w** [rasbt/mlxtend#571]
The following two lines don't seem to correspond to the description of the dataset above. Please could you check?
https://github.com/rasbt/mlxtend/blob/8e22fe5723fe6551f6ad76ffe64cf42911bb5c82/docs/sources/user_guide/data/loadlocal_mnist.ipynb#L50-L53

**Comment by rasbt** [comment]
Oops, that's a mistake indeed. Probably due to a copy-paste error. Will fix it. Thanks!
