### ISSUE TITLE
apriori.py has SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ziye9292** [rasbt/mlxtend#576]
Just ran the code in the association rule section but it throw the following error:

\apriori.py", line 191
    (iter_count, next_max_itemset), end="")
                                       ^
SyntaxError: invalid syntax

Not sure where the problem comes from. Thanks so much in advance for any suggestions on this problem!

**Comment by rasbt** [comment]
Hm, I am not getting this issue and the unit tests all pass ok. Things that come to mind are

a) are you maybe using Python 2.7?
b) have you accidentally edited the file?

Also, how are you exactly running the code? Is it an error that occurs upon importing `apriori`?

**Comment by ziye9292** [comment]
Yes, I am using Python 2.7.... Will that be a problem?

**Comment by rasbt** [comment]
That's probably an issue then. We dropped Python 2.7 support ~1/2 year ago and don't test for Python 2.7 anymore. Sorry, but you probably need to use Python 3.5-3.8 then

**Comment by ziye9292** [comment]
Oh, I am so sorry that I didn't realize the version issue here. I will close the the issue. Thank you for the help!

**Comment by rasbt** [comment]
No worries. Let me know if you encounter any other issues
