### ISSUE TITLE
Sequential Feature Selector with feature importance

### ISSUE THREAD

**Issue by lschneidpro** [rasbt/mlxtend#577]
Hi there,

I have been trying to apply RFE with lightGBM as my dataset contains some NaN.
It worked with mlxtend.feature_selection.SequentialFeatureSelector as compared to sklearn.feature_selection.RFECV that reject any dataset with NaN.

As I was interested of the ranking difference between feature_importance and other metrics, is there a way to rank on feature_importance with mlxtend.feature_selection.SequentialFeatureSelector please ?

**Comment by rasbt** [comment]
In SFS, due to how SFS works, there is no ranking for individual features. The ranking is for the subsets

For plotting the subset relevance, have a look at the docs at

http://rasbt.github.io/mlxtend/user_guide/feature_selection/SequentialFeatureSelector/#example-4-plotting-the-results
