### ISSUE TITLE
Aggregate ARM metrics for groups of stores

### ISSUE THREAD

**Issue by 99snowleopards** [rasbt/mlxtend#581]
thanks for releasing this amazing library! I have computed the ARM metrics (support, lift, ...) for a set of stores, by computing the metrics for each store individually;

 I need to compute the metrics for groups of stores from the store level metrics, say for all the stores in any state or county; (computing the metrics for different groups of stores directly is not an option)

 Is it possible to aggregate the ARM metrics this way? I'd greatly appreciate any guidance, thanks,

**Comment by rasbt** [comment]
Hm, there's currently no UI for aggregating the scores from the different stores. However, I suppose you could just compute the score average for each metric?

I.e., for a given rule, say you have

- support 0.5 in store 1
- support 0.6 in store 2
- support 0.7 in store 3

would (0.5+0.6+0.7)/3 = 0.6 make sense for your purpose work? In that case, this could be done using pandas on the resulting dataframes you obtained from each store.

**Comment by 99snowleopards** [comment]
thanks for replying @rasbt , we tried computing the average, but because of the significantly different transaction counts for the different products in the various stores, the average was not accurate for all the products,

 I'll leave this question open for now, in case someone has any other suggestions,

thanks again for releasing this amazing library!
