### ISSUE TITLE
Apriori results (Empty dataframe)

### ISSUE THREAD

**Issue by nucsit026** [rasbt/mlxtend#583]
What is the problem in my code of mlxtend apriori, I have a dataset of 17672 transactins, 12025 items, the result is(Empty dataframe)

> Basket = data.groupby("transactionid").apply(lambda x: list(x['itemid']))
> BasketData = list(BasketData)

> BasketList = list(BasketData)

> tc = TransactionEncoder()

> DataArry = tc.fit(BasketList).transform(BasketList, sparse=True)

> BasketSet = pd.SparseDataFrame(DataArry, columns=tc.columns_)

> FrequentItemsets = apriori(BasketSet, min_support=0.05,use_colnames=True)

**Comment by rasbt** [comment]
Hm,

can you show/print the BasketSet., e.g., via `BasketSet.head()`.

Maybe there is an issue with the formatting -- or, it could also be that there are no frequent items above that threshold ...

**Comment by nucsit026** [comment]
```python
# Importing required libraries 
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

#Importing Dataset 
data = pd.read_csv(r"C:\Users\moon\Desktop\Data\events.csv")
print ("The type of data at the begining is ","\n",data.dtypes,"\n")

# Droping rows of (view & addtocart) events
data.drop(data[data.event != "transaction"].index, inplace = True) 

# Dropping columns of (timestamp & event & visitorid) 
data.drop(["timestamp","event","visitorid"], axis = 1, inplace = True)
print ("The type of data after dropping is: ","\n",data.dtypes,"\n")

BasketData = data.groupby("transactionid").apply(lambda x: list(x['itemid']))
print ("The type of BasketData after grouping is:","\n",type(BasketData))

# Exporting dataframe to CSV file
BasketData.to_csv(r"C:\Users\moon\Desktop\Data\test.csv", index=False,sep =",")
print ("CSV file is exported")
```
The type of data at the begining is  
 timestamp          int64
visitorid          int64
event             object
itemid             int64
transactionid    float64
dtype: object 

The type of data after dropping is:  
 itemid             int64
transactionid    float64
dtype: object 

The type of BasketData after grouping is: 
 <class 'pandas.core.series.Series'> 

CSV file is exported
```python
# Converting panadas class from series into list
BasketData = list(BasketData)
print("The type of BasketData (Inner List) is: ",type(BasketData),"\n")

# Converting panadas class into list of lists
BasketList = list(BasketData)
print("The type of BasketData (Outer List) is: ",type(BasketList),"\n")

# Forming transactions into Boolean encoded by TransactionEncoder
tc = TransactionEncoder()
DataArry = tc.fit(BasketList).transform(BasketList)
print ("The number of items in numpy array is: ",DataArry.shape,"(transactions , items)

BasketSet = pd.DataFrame(DataArry, columns=tc.columns_)
print("The columns of the BasketSet dataframe are :","\n",BasketSet.columns,"\n")
print("The type of BasketSet is",type(BasketSet),"\n")
print("The BasketSet dataframe : ","\n",BasketSet.head())
print("This transaction has the first item (item 15):","\n",BasketSet.iloc[7368])
```
The number of items in numpy array is:  (17672, 12025) (transactions , items) 

The columns of the BasketSet dataframe are : 
 Int64Index([    15,     19,     25,     42,    147,    168,    199,    212,
               233,    304,
            ...
            466319, 466321, 466342, 466443, 466464, 466526, 466603, 466614,
            466710, 466861],
           dtype='int64', length=12025) 

The type of BasketSet is <class 'pandas.core.frame.DataFrame'> 

The BasketSet dataframe :  
    15      19      25      42      147     168     199     212     233     \
0   False   False   False   False   False   False   False   False   False   
1   False   False   False   False   False   False   False   False   False   
2   False   False   False   False   False   False   False   False   False   
3   False   False   False   False   False   False   False   False   False   
4   False   False   False   False   False   False   False   False   False   

   304     ...  466319  466321  466342  466443  466464  466526  466603  \
0   False  ...   False   False   False   False   False   False   False   
1   False  ...   False   False   False   False   False   False   False   
2   False  ...   False   False   False   False   False   False   False   
3   False  ...   False   False   False   False   False   False   False   
4   False  ...   False   False   False   False   False   False   False   

   466614  466710  466861  
0   False   False   False  
1   False   False   False  
2   False   False   False  
3   False   False   False  
4   False   False   False  

[5 rows x 12025 columns]
This transaction has the first item (item 15): 
 15         True
19        False
25        False
42        False
147       False
168       False
199       False
212       False
233       False
304       False
320       False
387       False
403       False
496       False
546       False
563       False
572       False
651       False
655       False
698       False
720       False
821       False
822       False
829       False
835       False
856       False
869       False
909       False
963       False
1022      False
          ...  
465622    False
465650    False
465680    False
465751    False
465811    False
465824    False
465833    False
465922    False
465943    False
465951    False
465977    False
466008    False
466079    False
466109    False
466114    False
466135    False
466161    False
466259    False
466263    False
466301    False
466319    False
466321    False
466342    False
466443    False
466464    False
466526    False
466603    False
466614    False
466710    False
466861    False
Name: 7368, Length: 12025, dtype: bool
```python
# Returning the items and itemsets with at least 5% support

FrequentItemsets = apriori(BasketSet, min_support=0.05,use_colnames=True)
print("FrequentItemsets are :",type(FrequentItemsets),"\n")
#pint(FrequentItemsets)
result = FrequentItemsets.empty
print(result)
```
FrequentItemsets are : <class 'pandas.core.frame.DataFrame'> 

True
******************************************************
[sample of test.txt](https://github.com/rasbt/mlxtend/files/3569036/sample.of.test.txt)

**That is all if have, sorrry for details**

**Comment by rasbt** [comment]
Hm, maybe there really aren't any frequent itemsets in this dataset. In order to find out, what you can try is to duplicate some rows of your dataset. Then, it should definitely return sth. 

E.g., where you have

    BasketList = list(BasketData)

add
    BasketList.extend(100*[BasketListt[0]])

On an example file like this, it would do the following:

```python
dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

dataset.extend(100*[dataset[0]])
print(dataset)
```

```
[['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
 ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
 ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs'],
 ['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
 ['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
...
```

**Comment by nucsit026** [comment]
I extended the dataset to 100 then 200, with min_support =0.05, but still same output

```

The type of BasketData (Inner List) is:  <class 'list'> 

The type of BasketData (Outer List) is:  <class 'list'> 

The number of items in numpy array is:  (17872, 12025) (transactions , items) 

FrequentItemsets are : <class 'pandas.core.frame.DataFrame'> 

Empty DataFrame
Columns: [support, itemsets]
Index: []
```
**Notes**:
1) the elements in exported CSV file are between square brackets for one element and square brackets and quotation marks for more than one.
```

[273872]
[316753]
[80858]
"[351124, 397642, 93556, 57548]"
[312728]
[153767]
[344421]
"[272976, 130226, 288078, 272770]"
"[127123, 213834, 31830, 195958]"
[171653]
[44001]

```
[CSV file.txt](https://github.com/rasbt/mlxtend/files/3574750/CSV.file.txt)
2) the output of outer list without single quotes ' :
```
The elements of BasketData (Outer List) are :  [[425758], [454430], [151855], [85842], [224184], [434289], [384506], [97890], [367588], [293363], [412917], [436344], [239235, 432742], [68672], [355099], [303715], [199874], [303637], [382885], [174074], [273872], [316753], [80858], [351124, 397642, 93556, 57548], [312728], [153767], [344421], [272976, 130226, 288078, 272770], [127123, 213834, 31830, 195958], [171653], [44001], [260732], ...
```
 Does this affect?

**Comment by rasbt** [comment]
Hard to tell, but based on the info you provided, I think there are issues with the way the file is formatted. The input format to the TransactionEncoder should be a list of lists. If you have 100 records, the "outer" list should have 100 lists. Each of the 100 lists should contain 1 or more entries. 

Based on what you are showing

> The elements of BasketData (Outer List) are :  [[425758], [454430], [151855], [85842]

It looks like that either

a) each record is a list of lists itself

or

b) each record consists of only a single item.

Could you share part of your dataset? I assume that "CSV file.txt" is not the dataset you are reading in, right? If it is the dataset you are using, how are you processign this into a valid Python list of lists?

**Comment by nucsit026** [comment]
Finally I figure out the problem (**as you said: there aren't any frequent itemsets in the dataset**), I extended to 200 with min_support 1% , then I have only found 14 frequent itemsets (unfortunately).

For "CSV file.txt", it is a txt copy of CSV file, it seems there is alot of transactoins have a single item.

I appreciate your help, thanks for your time.

**Comment by rasbt** [comment]
Ok, that's unfortunate. I guess we can close that then. If I were you, I would still double check whether the file is read into a Python list correctly though. Things like

    [344421]
    "[272976, 130226, 288078, 272770]"

look suspicious. I.e., it looks like a Python list of lists, not a CSV file. Also, due to the quotation marks, "[272976, 130226, 288078, 272770]" will probably be parsed as a single entry instead of 4 entries.

**Comment by jahidhasanlinix** [comment]
I am also getting the same problem with my large token items, all show FALSE, and when I apply apriori  it gives me nothing, any helps!



![screenshot](https://user-images.githubusercontent.com/36171973/144764640-57151c70-6f9d-4908-8bdf-1e5f56616cff.png)
![screenshot_1](https://user-images.githubusercontent.com/36171973/144764650-b8e40cde-3e97-432b-94ec-2cb9ce0e8e36.png)

**Comment by jahidhasanlinix** [comment]
I am also getting the same problem with my large token items, all show FALSE, and when I apply apriori it gives me nothing, any help
![screenshot_7](https://user-images.githubusercontent.com/36171973/144764670-c6337268-e966-4e53-a6ec-a04374e85f27.png)
s!
![screenshot_8](https://user-images.githubusercontent.com/36171973/144764675-47ba18b5-0743-4c16-93c2-895406ee3ad5.png)

**Comment by rasbt** [comment]
Hi there,
based on the "..." in the data frame it is not possible to tell whether all entries are False. It's probably just a sparse array. You can set the `min_support` to a lower value and see if you get any results.

**Comment by jahidhasanlinix** [comment]
I tried setting it to lower value, same problem happens even when I use` min_support=0.6` something like that.

**Comment by rasbt** [comment]
can you set it to 0.001

**Comment by jahidhasanlinix** [comment]
So I tried with this and got an MemoryError- attached the screensho
![screenshot](https://user-images.githubusercontent.com/36171973/144765755-26849d7c-daee-4f55-bcf7-1caec47c2209.png)
t

**Comment by jahidhasanlinix** [comment]
I just changed it to `min_support=0.09` and it works but why it's not working for a different set like 10/100/200 as it's a large dataset so I was thinking to use a larger set instead of something small. Any suggestions-
![fafaf](https://user-images.githubusercontent.com/36171973/144765853-6eeda8e3-6764-486d-8ba4-6bccc5a62635.png)

To check with something different: like taking `min_support=0.5` it does not work at this set value.
![afafa](https://user-images.githubusercontent.com/36171973/144765900-4a42a436-85a3-4e8e-9bfd-65a81cdeeece.png)


Why is this difference actually, in this case, even the code is correct I believe based on my lists of items, right.

**Comment by rasbt** [comment]
The support is a value between [0, 1], so it's a proportion. There should probably be a warning if someone selects a support greater than 1. Certain cases are probably rare in the large dataset, which is why you see different results when you use a small vs. large dataset.

**Comment by jahidhasanlinix** [comment]
I see, I got your point. Actually, the requirement was using min_sup=200 for this dataset but seems it's not possible as you mentioned the ranges should be between 0 to 1 based on the algorithm itself. If I understand it correctly.

**Comment by rasbt** [comment]
Yes, that's correct. The support is computed as `transactions_where_item(s)_occur / total_transactions`. So, if you choose a support of 0.09, this means that 9% of the data records contain this item.

**Comment by jahidhasanlinix** [comment]
Thank you so much for the explanation and help, highly appreciate that.

**Comment by viralrjani** [comment]
[SalesReport.xlsx](https://github.com/rasbt/mlxtend/files/9438236/SalesReport.xlsx)
Hi,

I am facing the issue of "ValueError: The allowed values for a DataFrame are True, False, 0, 1. Found value nan"
Below is the code which I am using for reference.

Code:
#importing libraries
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
df = pd.read_excel('/content/sample_data/SalesReport.xlsx')

#data cleaning
df['Product Name'] = df['Product Name'].str.strip()
df.dropna(axis=0,subset=['Invoice No.'], inplace=True)
df['Invoice No.'] = df['Invoice No.'].astype('str')

#matrix transformation
basket = (df.groupby(['Invoice No.','Product Name'])['QTY']
           .sum().unstack().reset_index().fillna(0)
           .set_index('Invoice No.'))
 
 #encoding to 0 & 1
 def encode_units(x):
  if x <= 0:
    return 0
  if x >= 1:
    return 1
basket_sets = basket.applymap(encode_units)

Now facing error while using apriori
frequent_itemsets = apriori(basket_sets, min_support = 0, use_colnames = True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.head()

Error:
ValueError                                Traceback (most recent call last)
[<ipython-input-43-02a32b2af81e>](https://localhost:8080/#) in <module>
----> 1 frequent_itemsets = apriori(basket_sets, min_support = 0, use_colnames = True)
      2 rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
      3 rules.head()

[/usr/local/lib/python3.7/dist-packages/mlxtend/frequent_patterns/apriori.py](https://localhost:8080/#) in apriori(df, min_support, use_colnames, max_len, n_jobs)
    109             s = ('The allowed values for a DataFrame'
    110                  ' are True, False, 0, 1. Found value %s' % (val))
--> 111             raise ValueError(s)
    112 
    113     is_sparse = hasattr(df, "to_coo")

ValueError: The allowed values for a DataFrame are True, False, 0, 1. Found value nan

Can someone please help in identifying the issue as I could not find not a number in dataframe "basket_sets "

**Comment by NimaSarajpoor** [comment]
@viralrjani 
I think it would be better if you provide your code like this:
```
my code
```

You can create this by using ``` before and after the "my code". It would be easier for others to read your code.


---

Can you do `df.isnull().sum(axis=0)` just right after reading the file (i.e. before the `#data cleaning`) and provide the result here?

**Comment by viralrjani** [comment]
`#importing libraries
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
df = pd.read_excel('/content/sample_data/SalesReport.xlsx')

#data cleaning
df['Product Name'] = df['Product Name'].str.strip()
df.dropna(axis=0,subset=['Invoice No.'], inplace=True)
df['Invoice No.'] = df['Invoice No.'].astype('str')

#matrix transformation
basket = (df.groupby(['Invoice No.','Product Name'])['QTY']
.sum().unstack().reset_index().fillna(0)
.set_index('Invoice No.'))

#encoding to 0 & 1
def encode_units(x):
if x <= 0:
return 0
if x >= 1:
return 1
basket_sets = basket.applymap(encode_units)

Now facing error while using apriori
frequent_itemsets = apriori(basket_sets, min_support = 0, use_colnames = True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.head()`

**Comment by viralrjani** [comment]
`#importing libraries
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules
df = pd.read_excel('/content/sample_data/SalesReport.xlsx')

#data cleaning
df['Product Name'] = df['Product Name'].str.strip()
df.dropna(axis=0,subset=['Invoice No.'], inplace=True)
df['Invoice No.'] = df['Invoice No.'].astype('str')

#matrix transformation
basket = (df.groupby(['Invoice No.','Product Name'])['QTY']
.sum().unstack().reset_index().fillna(0)
.set_index('Invoice No.'))

#encoding to 0 & 1
def encode_units(x):
if x <= 0:
return 0
if x >= 1:
return 1
basket_sets = basket.applymap(encode_units)

Now facing error while using apriori
frequent_itemsets = apriori(basket_sets, min_support = 0, use_colnames = True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.head()`

sure thanks

**Comment by viralrjani** [comment]
@NimaSarajpoor: Thanks for the suggestion and reply.

After posting the query and trying out different possibilities I was able to solve the issue at basket_set level by 

```
basket_sets = basket_set.fillna(0)
```

Getting the same amount of rows x col. But not sure which data point was creating the issue.
p.s.: I will also try the suggested solution.

**Comment by NimaSarajpoor** [comment]
It is good that you solved it. 

> p.s.: I will also try the suggested solution.

I was trying to get an idea about nan values in your data. It is usually helpful to get an idea about the number of missing values per feature and knowing the `dtype` of each feature. So, that might give you some idea to track down the issue.
