### ISSUE TITLE
plot_confusion_matrix inappropriate font color 

### ISSUE THREAD

**Issue by sohrabtowfighi** [rasbt/mlxtend#586]
Thanks for your project.

I used `plot_confusion_matrix` using some of my data and came up with the following.

[https://imgur.com/a/TdYChzg](https://imgur.com/a/TdYChzg)

Should not the bottom left square have black font?

**Comment by sohrabtowfighi** [comment]
I put in a pull request [588](https://github.com/rasbt/mlxtend/pull/588)

**Comment by sohrabtowfighi** [comment]
[plot_decision_regions.zip](https://github.com/rasbt/mlxtend/files/3613285/plot_decision_regions.zip)

**Comment by rasbt** [comment]
I am a bit careful with zip files from the web. Could you just push the changes in the PR you opened? No worries if it is incomplete, I can take it from there

**Comment by sohrabtowfighi** [comment]
done

**Comment by rasbt** [comment]
awesome thx! Will take of the PR then!
