### ISSUE TITLE
problem with "FROM mlxtend.plotting IMPORT plot_decision_regions"

### ISSUE THREAD

**Issue by mrn314159** [rasbt/mlxtend#587]
I have problems importing plot_decision_regions from mlxtend.plotting. I have correctly installed mlxtend and I can import it in python3 without problems. I am a beginner in machine learning, this error seems to me to be an error in the code. Can someone help me to figure it out?

>>> from mlxtend.plotting import plot_decision_regions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marianna/.local/lib/python3.5/site-packages/mlxtend/plotting/__init__.py", line 15, in <module>
    from .heatmap import heatmap
  File "/home/marianna/.local/lib/python3.5/site-packages/mlxtend/plotting/heatmap.py", line 74
    raise AssertionError(f'len(row_names) (got {len(row_names)})'
                                                                                                      ^
SyntaxError: invalid syntax

**Comment by rasbt** [comment]
I think the culprit here is the f-string in the line

    raise AssertionError(f'len(row_names) (got {len(row_names)})'

There is a feature that was added to Python 3.6 called "f-strings" (some examples here: https://cito.github.io/blog/f-strings/), which make string formatting easier. However, f-strings were introduced in Python 3.6 and I see based on the 4th line that you are using Python 3.5.

Can you upgrade to Python 3.6 or Python 3.7?

**Comment by mrn314159** [comment]
Thank you for your fast reply. I have just installed python 3.6 and now it seems to work well. I am able to import plot_decision_regions successfully.

**Comment by rasbt** [comment]
Nice, glad to hear that installing 3.6 solved this issue.

**Comment by SarnathK** [comment]
Another way to solve is to install "pip install mlxtend==0.13.0"
The 0.13.0 package does not have this problem. I dont know about other versions like 14, 15 etc.. I think the one with 0.17.0 did not work and had this problem....
This is easier than changing Python version.

**Comment by suryahbs75** [comment]
Thanks Sarnath, just installing the version 0.13.0 worked for me without changing the Python version.  Good one and helped me a lot.
