### ISSUE TITLE
Issue with GridSearchCV and SFS to find best parameters and features with SVM regressor

### ISSUE THREAD

**Issue by mycarta** [rasbt/mlxtend#591]
I am trying to replicate [SFS Example 8](http://rasbt.github.io/mlxtend/user_guide/feature_selection/SequentialFeatureSelector/#example-8-sequential-feature-selection-and-gridsearch), but using my own data, and also a few tweaks (e.g. using leave one out crossvalidation and SVM regressor with rbf kernel)

When I get to the last cell of the example:
```
for i in range(len(sfs.cv_results_['params'])):
    print(sfs.cv_results_['params'][i], 'test acc.:', sfs.cv_results_['mean_test_score'][i])
```
I get this error:
![image](https://user-images.githubusercontent.com/7424763/65354674-5564b800-dbad-11e9-8169-465c7a96e936.png)

Below is a minimal reproducible example:

```
# import required modules
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.model_selection import LeaveOneOut, GridSearchCV, train_test_split
from sklearn.pipeline import Pipeline
from sklearn.metrics import make_scorer, mean_squared_error
from sklearn import svm, preprocessing

# data loading scaling, splitting
url= 'https://raw.githubusercontent.com/mycarta/Data-science-tools-petroleum-exploration-and-production/master/Python/data/Table2_Hunt_2013_edit.csv'
data = pd.read_csv(url).astype('float64')
y =  data['Production']
X = data.drop('Production',axis=1)
scaled_X = preprocessing.StandardScaler().fit_transform(X)
scaled_X_df = pd.DataFrame(scaled_X, index=X.index, columns=X.columns)
train_X, val_X, train_y, val_y = train_test_split(scaled_X_df, y, test_size= 0.2, random_state=99)

# set-up scoring and crossvalidation 
scorer = make_scorer(mean_squared_error, greater_is_better=False)
loo = LeaveOneOut()

#this one to prevent warning about gamma settings
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

# pipeline
svrr = svm.SVR(cache_size = 800, epsilon = 0.01)

sfs = SFS(estimator=svrr, 
          k_features=1, 
          forward=False, 
          floating=True, 
          scoring=scorer,
          cv = loo,
          n_jobs = -1)

pipe = Pipeline([('sfs', sfs), 
                 ('svr', svrr)])

parm_grid=[
    {'C': [0.1, 0.5, 1, 3, 5, 7, 9, 11, 13, 15],
     'gamma':[0.0005, 0.0002, 0.0001, 0.001, 0.01, 0.1, 1, 2]}
    ]

grid_search = GridSearchCV(estimator=pipe, 
                           param_grid=parm_grid,
                           scoring=scorer,
                           cv=loo,
                          iid=True,
                          refit=False)

sfs = sfs.fit(train_X, train_y)

# getting out the info I want
for i in range(len(sfs.cv_results_['params'])):
    print(sfs.cv_results_['params'][i], 'test acc.:', sfs.cv_results_['mean_test_score'][i])
```

**Comment by rasbt** [comment]
Hi there. Based on the example, it seems that you are trying to access `sfs.cv_results_`. However, `.cv_results_` is a `GridSearchCV` attribute, so it should probably be `gridsearch.cv_results_`.

Also, you probably meant to type `grid_search.fit(train_X, train_y)` not `sfs.fit(train_X, train_y)`; otherwise, the `grid_search` won't be doing anything.

**Comment by mycarta** [comment]
Thanks @rasbt 
OF course, those are right. Typical typos.

I have changed my `pipeline` cell to:

```
svrr = svm.SVR(cache_size = 800, epsilon = 0.01)
sfs = SFS(estimator=svrr, 
          k_features=1, 
          forward=False, 
          floating=True, 
          scoring=scorer,
          cv = loo,
          n_jobs = -1)
pipe = Pipeline([('sfs', sfs), 
                 ('svr', svrr)])
parm_grid=[
    {'C': [0.1, 0.5, 1, 3, 5, 7, 9, 11, 13, 15],
     'gamma':[0.0005, 0.0002, 0.0001, 0.001, 0.01, 0.1, 1, 2]}
    ]
grid_search = GridSearchCV(estimator=pipe, 
                           param_grid=parm_grid,
                           scoring=scorer,
                           cv=loo,
                           n_jobs = -1,
                          iid=True,
                          refit=False)
# run gridearch
grid_search.fit(train_X, train_y)
```

but now I get this error:

> --------------------------------------------------------------------------
> _RemoteTraceback                          Traceback (most recent call last)
> _RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\externals\joblib\externals\loky\process_executor.py", line 418, in _process_worker
>     r = call_item()
>   File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\externals\joblib\externals\loky\process_executor.py", line 272, in __call__
>     return self.fn(*self.args, **self.kwargs)
>   File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 567, in __call__
>     return self.func(*args, **kwargs)
>   File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 225, in __call__
>     for func, args, kwargs in self.items]
>   File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py", line 225, in <listcomp>
>     for func, args, kwargs in self.items]
>   File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 514, in _fit_and_score
>     estimator.set_params(**parameters)
>   File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\pipeline.py", line 147, in set_params
>     self._set_params('steps', **kwargs)
>   File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\metaestimators.py", line 52, in _set_params
>     super(_BaseComposition, self).set_params(**params)
>   File "C:\Users\user\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\base.py", line 215, in set_params
>     (key, self))
> ValueError: Invalid parameter C for estimator Pipeline(memory=None,
>      steps=[('sfs', SequentialFeatureSelector(clone_estimator=True, cv=LeaveOneOut(),
>              estimator=SVR(C=1.0, cache_size=800, coef0=0.0, degree=3, epsilon=0.01,
>   gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
>   tol=0.001, verbose=False),
>              floating=True, forward...
>   gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
>   tol=0.001, verbose=False))]). Check the list of available parameters with `estimator.get_params().keys()`.
> """
> 
> The above exception was the direct cause of the following exception:
> 
> ValueError                                Traceback (most recent call last)
> <ipython-input-9-3929408280ee> in <module>
>      27 
>      28 # run gridearch
> ---> 29 grid_search.fit(train_X, train_y)
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_search.py in fit(self, X, y, groups, **fit_params)
>     720                 return results_container[0]
>     721 
> --> 722             self._run_search(evaluate_candidates)
>     723 
>     724         results = results_container[0]
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_search.py in _run_search(self, evaluate_candidates)
>    1189     def _run_search(self, evaluate_candidates):
>    1190         """Search all candidates in param_grid"""
> -> 1191         evaluate_candidates(ParameterGrid(self.param_grid))
>    1192 
>    1193 
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_search.py in evaluate_candidates(candidate_params)
>     709                                for parameters, (train, test)
>     710                                in product(candidate_params,
> --> 711                                           cv.split(X, y, groups)))
>     712 
>     713                 all_candidate_params.extend(candidate_params)
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in __call__(self, iterable)
>     928 
>     929             with self._backend.retrieval_context():
> --> 930                 self.retrieve()
>     931             # Make sure that we get a last message telling us we are done
>     932             elapsed_time = time.time() - self._start_time
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\externals\joblib\parallel.py in retrieve(self)
>     831             try:
>     832                 if getattr(self._backend, 'supports_timeout', False):
> --> 833                     self._output.extend(job.get(timeout=self.timeout))
>     834                 else:
>     835                     self._output.extend(job.get())
> 
> ~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py in wrap_future_result(future, timeout)
>     519         AsyncResults.get from multiprocessing."""
>     520         try:
> --> 521             return future.result(timeout=timeout)
>     522         except LokyTimeoutError:
>     523             raise TimeoutError()
> 
> ~\AppData\Local\Continuum\anaconda3\lib\concurrent\futures\_base.py in result(self, timeout)
>     430                 raise CancelledError()
>     431             elif self._state == FINISHED:
> --> 432                 return self.__get_result()
>     433             else:
>     434                 raise TimeoutError()
> 
> ~\AppData\Local\Continuum\anaconda3\lib\concurrent\futures\_base.py in __get_result(self)
>     382     def __get_result(self):
>     383         if self._exception:
> --> 384             raise self._exception
>     385         else:
>     386             return self._result
> 
> ValueError: Invalid parameter C for estimator Pipeline(memory=None,
>      steps=[('sfs', SequentialFeatureSelector(clone_estimator=True, cv=LeaveOneOut(),
>              estimator=SVR(C=1.0, cache_size=800, coef0=0.0, degree=3, epsilon=0.01,
>   gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
>   tol=0.001, verbose=False),
>              floating=True, forward...
>   gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
>   tol=0.001, verbose=False))]). Check the list of available parameters with `estimator.get_params().keys()`.

 Just to be sure it is not just the parameter C I also run the grid search with just:

```
parm_grid=[ 
    {'gamma':[0.0005, 0.0002, 0.0001, 0.001, 0.01, 0.1, 1, 2]}
    ]
```
 which throws the error:

> ValueError: Invalid parameter gamma for estimator Pipeline(memory=None,
>      steps=[('sfs', SequentialFeatureSelector(clone_estimator=True, cv=LeaveOneOut(),
>              estimator=SVR(C=1.0, cache_size=800, coef0=0.0, degree=3, epsilon=0.01,
>   gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
>   tol=0.001, verbose=False),
>              floating=True, forward...
>   gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
>   tol=0.001, verbose=False))]). Check the list of available parameters with `estimator.get_params().keys()`.

This rather seems like a scikit-learn error, but just in case, have you encountered it?

I can also turn this into a SO question, so that you might answer there, if you prefer.

**Comment by mycarta** [comment]
OK, having read your example and the error message better, it looks like the issue was now with the syntax for `param_grid`

Once I changed it to:
```
parm_grid=[ 
    {'sfs__estimator__C': [0.1, 0.5, 1, 3, 5, 7, 9, 11, 13, 15],
     'sfs__estimator__gamma':[0.0005, 0.0002, 0.0001, 0.001, 0.01, 0.1, 1, 2]}
    ]
```

I got everything to run properly.
