### ISSUE TITLE
Find a replacement for landscape.io for checking code health

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#599]
Seems like https://landscape.io has been offline for a couple of months. When visiting the website, it says "back soon ...". Not sure if/when they will be back soon. We should probably consider alternative services at this point.

Any suggestions?

**Comment by ecederstrand** [comment]
Codacy has been a pleasant experience for me after also giving up on landscape.io

**Comment by rasbt** [comment]
Thanks, will have a look!

**Comment by rasbt** [comment]
I just set it up earlier today, and it does seem to be very nice indeed! Thanks for the recommendation!
