### ISSUE TITLE
verbose on EnsembleClassifier

### ISSUE THREAD

**Issue by albahnsen** [rasbt/mlxtend#6]
Hi, any plans to include a verbose option. I modify the code just to know which clf is being trained, but is far from ideal

**Comment by rasbt** [comment]
Hi, Alejandro,
thanks for the suggestion, that sounds useful. You mean sth like

    Fitting 5 classifiers...
    Fitting clf1: LogisticRegression (1/5)
    Fitting clf2: LogisticRegression (2/5)    
    Fitting clf3: SVC (3/5)    
    Fitting clf4: RandomForest (4/5)    
    Fitting clf5: Perceptron (5/5)    

Or in a higher "verbosity" level:

    Fitting 5 classifiers...
    Fitting clf1: LogisticRegression (1/5)
        {'random_state': None, 'intercept_scaling': 1, 'penalty': 'l2', 'multi_class': 'ovr', 'max_iter': 100, 'C': 1.0, 'class_weight': None, 'solver': 'liblinear', 'tol': 0.0001, 'verbose': 0, 'fit_intercept': True, 'dual': False}
    ...

?

**Comment by albahnsen** [comment]
yeah that looks great. it is already done? I could help (in a couple of days)

**Comment by rasbt** [comment]
Nice. Feel free to add it if you like, otherwise I could do it to, it shouldn't be much work, just let me know! I think we should start with 3 verbosity levels

    `verbose=0` (default): prints nothing like right now
    `verbose=1`: the 1st scenario shown above
    `verbose=2`: the 2nd scenario shown above

For example for `verbose=1`:
    from sklearn.pipeline import _name_estimators

    clf1 = LogisticRegression(random_state=1)
    clf2 = RandomForestClassifier(random_state=1)
    eclf = EnsembleClassifier(clfs=[clf1, clf1, clf2], voting='soft')

    for i,n in enumerate(_name_estimators(eclf.clfs)):
        print('Fitting clf%d: %s (%d/%d)' %(i+1, n[0], i+1, len(eclf.clfs)))

**Comment by albahnsen** [comment]
I'm giving it a try

Should the verbose parameter be passed to the underlying clf?
maybe as:
```
if hasattr(clf, 'verbose'):
    clf.set_params(verbose=verbose)
```

**Comment by rasbt** [comment]
yes, that sounds like a good idea!
