### ISSUE TITLE
Count number of possible association rules using mlxtend

### ISSUE THREAD

**Issue by KafeelBasha** [rasbt/mlxtend#604]
Hello

How to count total number of possible association rules using mlxtend?. Any suggestion will be helpful.

Thanks
Kafeel

**Comment by rasbt** [comment]
You could use the data frame's `shape` attribute, e.g., 

    df = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)
    print("Number of rules", df.shape[0])

Or do you mean the number of possible rules irrespective of the score threshold?

**Comment by KafeelBasha** [comment]
Thank you for the response.

Yes, I want to find the number of possible rules irrespective of the score threshold.

Kafeel

**Comment by rasbt** [comment]
It's basically based on the number of combinations, i.e., "n choose k" for each different set of unique entries. It's a bit complicated to compute this by hand, because you would now the different frequent itemset entries. However, you can use the following code to count the number through simulation:

## 1) Suppose you have a frequent itemset array as follows:

```python
import pandas as pd
import numpy as np
from itertools import combinations
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori


dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
```

## 2) This code will give you the number of possible rules:

```python
df = frequent_itemsets

keys = df['itemsets'].values
values = df['support'].values
frozenset_vect = np.vectorize(lambda x: frozenset(x))
frequent_items_dict = dict(zip(frozenset_vect(keys), values))

count = 0
for k in frequent_items_dict.keys():
    # to find all possible combinations
    for idx in range(len(k)-1, 0, -1):
        # of antecedent and consequent
        for c in combinations(k, r=idx):
            antecedent = frozenset(c)
            consequent = k.difference(antecedent)
            count += 1
```

**Comment by KafeelBasha** [comment]
Thanks a lot.
