### ISSUE TITLE
Standalone `average_per_class_accuracy` function

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#617]
Make a standalone `average_per_class_accuracy_score` function akin to https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html

**Comment by deepandas11** [comment]
Hello!
I would like to work on this.

**Comment by rasbt** [comment]
Hi, there.

Yes, that's correct, it would be a standalone function for computing the accuracy for a given class. It would be similar to accuracy_score but then also include a "pos_label" argument like `f1_score` (https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html#sklearn.metrics.f1_score)

**Comment by ElhamSol** [comment]
Hi,

The current f1-score doesn't support multiclass problems.
Would it be possible that you could add it? like weighted F-score or macro F-score as in (https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html#sklearn.metrics.f1_score).

**Comment by rasbt** [comment]
Thanks for the note. I agree that this would be a good thing to do some time. Or maybe phasing out metrics that are implemented in sklearn to avoid duplicating efforts.

**Comment by ElhamSol** [comment]
Can you suggest me a quick fix to this?
I'm dealing with a multiclass imbalanced problem and accuracy is not a good measure to pick the features.

**Comment by rasbt** [comment]
What's the exact issue? I.e., in which context does the F1 score not work? Btw. regarding accuracy & imbalanced problems, there are also 2 versions (balanced & average per-class accuracy): http://rasbt.github.io/mlxtend/user_guide/evaluate/accuracy_score/#example-2-per-class-accuracy

**Comment by ElhamSol** [comment]
Hi,
Sorry for the delay.

When I'm running the following on a multi-class problem:

```

from mlxtend.feature_selection import SequentialFeatureSelector as sfs
from mlxtend.plotting import plot_sequential_feature_selection as plot_sfs
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
import matplotlib.pyplot as plt
# Estimator
estimator = XGBClassifier()
# Step Forward Feature Selector
StepForward = sfs(estimator,k_features=(1, data.shape[1]),forward=True,floating=True,verbose=2,scoring='f1',cv=5, n_jobs=-1)
#Scoring metric in {accuracy, f1, precision, recall, roc_auc}
pipe = make_pipeline(StandardScaler(), StepForward)
pipe.fit(X,y)


```

I get the following error:
```
ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].
```

When I try to use average= 'weighted' as below:

```
data.shape[1]),forward=True,floating=True,verbose=2,scoring='f1',average='weighted',cv=5, n_jobs=-1)
```

I get this error:
```
TypeError: __init__() got an unexpected keyword argument 'average'
```


I would appreciate it if you could let me know how I can select the average per class accuracy.
