### ISSUE TITLE
Correcting documentation: online annotations via hypothesis

### ISSUE THREAD

**Issue by hmf** [rasbt/mlxtend#62]
Hello,

While looking at the feature selection documentation at:

http://rasbt.github.io/mlxtend/user_guide/feature_selection/SequentialFeatureSelector/

I have come across several typos. In order to facilitate quick annotations of the text maybe the following tool is useful:

https://hypothes.is/

Anyone can comment, ask questions, suggest alterations and point out typos quickly. In this way the maintainer has access to the location and comment in a single web-page.

HTHs

**Comment by rasbt** [comment]
Thanks for the feedback! Yeah, running the texts through a spell checker has been too long on my to do list! I will get to it some time soon. The tool you mentioned looks pretty useful; please don't hesitate to send me a link with the annotations if you like!

**Comment by hmf** [comment]
Here you are:

https://via.hypothes.is/http://rasbt.github.io/mlxtend/user_guide/feature_selection/SequentialFeatureSelector/

HTHs

**Comment by rasbt** [comment]
Wow, that's a bunch of pretty embarrassing typos :) Thanks for taking the time to annotate them, I really appreciate that. I wrote the docs in IPython Nb, and I am still looking for a good (i.e., "convenient") way to run a spellcheck on these to catch such obvious things; maybe I will work with the Markdown files that are generated from the Nbs ... In any case, I applied the fixes, and I am looking forward to incorporate a some spellchecking tool in my workflow here :).

**Comment by hmf** [comment]
You can use the extensions [1] to check spelling. Their are a few but I use calico's [2] - not perfect. 
In order to install do the following:

jupyter nbextension install --user https://bitbucket.org/ipre/calico/downloads/calico-spell-check-1.0.zip
    jupyter nbextension install --user https://bitbucket.org/ipre/calico/downloads/calico-document-tools-1.0.zip
    jupyter nbextension install --user https://bitbucket.org/ipre/calico/downloads/calico-cell-tools-1.0.zip
    jupyter nbextension enable calico-spell-check
    jupyter notebook
    Create a markdown cell
    Make sure you have the "Toggle spell checking on a markdown cell" in the tool bar (t the right of the cell mode)

Other references include [3]. Note tha Calico's project site is not active, so maybe another solution may be more appropriate. 

HTHs

[1] https://github.com/ipython-contrib/IPython-notebook-extensions
[2]  https://bitbucket.org/ipre/calico/
[3] http://www.simulkade.com/posts/2015-04-07-spell-checking-in-jupyter-notebooks.html

**Comment by rasbt** [comment]
That's great thanks a lot! Had troubles setting it up this way though. I searched a bit and found that the project was moved to https://github.com/Calysto/notebook-extensions ... also here, no luck with the instructions. Finally, I got it to work then, the problem was that it was creating a `notebook-extensions-master` subdir inside the `nbextensions`. Now, everything works fine, thanks for the suggestion!

Just in case it may come handy in future, here's how I got it to work:

```
~$ jupyter nbextension install https://github.com/Calysto/notebook-extensions/archive/master.zip --user

Extracting: /var/folders/cn/5d4pkx3561xc7yyz19mp11nh0000gn/T/tmp514jeedb/master.zip -> /Users/Sebastian/Library/Jupyter/nbextensions

~$ jupyter nbextension enable calico-document-tools

Enabling notebook extension calico-document-tools...
      - Validating: problems found:
        - require?  X calico-document-tools

~$ ls /Users/Sebastian/Library/Jupyter/nbextensions
notebook-extensions-master

~$ mv /Users/Sebastian/Library/Jupyter/nbextensions/notebook-extensions-master/* /Users/Sebastian/Library/Jupyter/nbextensions/

~$ jupyter nbextension enable calico-document-tools

Enabling notebook extension calico-document-tools...
      - Validating: OK

```
