### ISSUE TITLE
Sequential Feature Selection and GridSearch : access the indices of the best features

### ISSUE THREAD

**Issue by hmf** [rasbt/mlxtend#63]
Hello,

This is a question.  

I am using example 7 in:

http://rasbt.github.io/mlxtend/user_guide/feature_selection/SequentialFeatureSelector/

I would like to access the indices of the selected features. When I use:

```python
sfs1.k_feature_idx_
```
as shown in example 1, I get the error:

```python
AttributeError                            Traceback (most recent call last)
<ipython-input-76-92f3d7e599b6> in <module>()
----> 1 sfs1.k_feature_idx_

AttributeError: 'SequentialFeatureSelector' object has no attribute 'k_feature_idx_'
```

I also tried to use:

```python
gs.transform()
```
but got the following error:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-102-98472ed5822d> in <module>()
----> 1 gs.transform()

/home/hmf/my_py3/lib/python3.4/site-packages/sklearn/utils/metaestimators.py in __get__(self, obj, type)
     33             # delegate only on instances, not the classes.
     34             # this is to allow access to the docstrings.
---> 35             self.get_attribute(obj)
     36         # lambda, but not partial, allows help() to work with update_wrapper
     37         out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)

/home/hmf/my_py3/lib/python3.4/site-packages/sklearn/utils/metaestimators.py in __get__(self, obj, type)
     33             # delegate only on instances, not the classes.
     34             # this is to allow access to the docstrings.
---> 35             self.get_attribute(obj)
     36         # lambda, but not partial, allows help() to work with update_wrapper
     37         out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)

AttributeError: 'KNeighborsClassifier' object has no attribute 'transform'
```

So how do I access this information without having to search for the features again?

TIA

P.S: I requested membership to the Gougle group but I have not had a reply and it does not seem to be used.

**Comment by rasbt** [comment]
Thanks again for pointing this out. In short, the reason is that `GridSearchCV` clones the estimator -- it doesn't modify the "original" `sfs1` object. Thus, to get further insight into `sfs1`'s attributes, you'd need to set the `refit=True` inside the `GridSearchCV` or refit the `sfs1` pipeline using the `best_params_` from grid search. I added an example to the documentation under the ["Example 7" section](http://rasbt.github.io/mlxtend/user_guide/feature_selection/SequentialFeatureSelector/#example-7-sequential-feature-selection-and-gridsearch)
Thanks!

**Comment by hmf** [comment]
Thank you.
