### ISSUE TITLE
Getting module not callable error

### ISSUE THREAD

**Issue by kedarthakar** [rasbt/mlxtend#637]
rom sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

boston = load_boston()
X, y = boston.data, boston.target

lr = LinearRegression()

sfs1 = sfs(lr, 
          k_features=13, 
          forward=True, 
          floating=False, 
          scoring='neg_mean_squared_error',
          cv=10)

sfs1 = sfs1.fit(X, y)
fig = plot_sfs(sfs1.get_metric_dict(), kind='std_err')

plt.title('Sequential Forward Selection (w. StdErr)')
plt.grid()
plt.show()

I am running this code in Jupyter notebook, Anaconda 1.9.7, Python 3

I get the following error - 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-47-af5c318a9e63> in <module>
     12           floating=False,
     13           scoring='neg_mean_squared_error',
---> 14           cv=10)
     15 
     16 sfs1 = sfs1.fit(X, y)

TypeError: 'module' object is not callable

Can someone help?

Br

Kedar

**Comment by rasbt** [comment]
Regarding the line

> sfs1 = sfs(lr, ...

How did you import sfs?

**Comment by kedarthakar** [comment]
Hi

I used 

from mlxtend.feature_selection import sequential_feature_selector as sfs

**Comment by rasbt** [comment]
It should be

> from mlxtend.feature_selection import SequentialFeatureSelector as sfs

Changing that will fix that issue :).
