### ISSUE TITLE
The requirement matplotlib>=3.0.0 (fro m mlxtend)

### ISSUE THREAD

**Issue by dengwen168** [rasbt/mlxtend#642]
I tried to install mlxtend, I got the following error:

Collecting matplotlib>=3.0.0 (from mlxtend)
  Could not find a version that satisfies the requirement matplotlib>=3.0.0 (fro
m mlxtend) (from versions: )
No matching distribution found for matplotlib>=3.0.0 (from mlxtend)

Could somebody tell me how to fix this problem? thanks.

**Comment by rasbt** [comment]
Hm weird that conda/pip doesn't find it. There is already matplotlib version 3.1.1.. Could you try to install matplotlib separately first? E.g.,

    conda install matplotlib==3.1.1

or 

    pip install matplotlib==3.1.1

**Comment by michalz92** [comment]
In my case, I was running `pip install` whereas you have to run `pip3 install` (or `python3 -m pip install`) on Linux.

**Comment by rasbt** [comment]
oh yeah, that's if you have Python 2.7 alongside Python 3 in your OS. Should have mentioned that.

**Comment by rasbt** [comment]
Since we removed support for Py 2.7 last year, I think this can be closed.

**Comment by eduardojsbarroso** [comment]
> In my case, I was running `pip install` whereas you have to run `pip3 install` (or `python3 -m pip install`) on Linux.

Thx. It was the pip3 that solved for me
