### ISSUE TITLE
FPMax: Index Error: list index is out of range

### ISSUE THREAD

**Issue by MLivanos** [rasbt/mlxtend#647]
Versions:
Python 3.7.4
MLXtend: 0.17.0
numpy: 1.17.2

I induce the following error while running the fpmax frequent pattern function. I can confirm that the dataframe is in the correct format, and is initialized via the MLXtend TransactionEncoder, as in examples, and that minsup is within range (1.0). This error occurs for all values of minsup on my data. 
len(self.nodes) and len(itemset) both return 0.
The line that induces the error in my code is:

`x = fpmax(self.transactions, min_support=minsup)`

`File "/usr/local/lib/python3.7/site-packages/mlxtend/frequent_patterns/fpmax.py", line 74, in fpmax
    return fpc.generate_itemsets(generator, len(df.values), colname_map)
  File "/usr/local/lib/python3.7/site-packages/mlxtend/frequent_patterns/fpcommon.py", line 37, in generate_itemsets
    for sup, iset in generator:
  File "/usr/local/lib/python3.7/site-packages/mlxtend/frequent_patterns/fpmax.py", line 82, in fpmax_step
    if not mfit.contains(largest_set):
  File "/usr/local/lib/python3.7/site-packages/mlxtend/frequent_patterns/fpmax.py", line 160, in contains
    for basenode in self.nodes[itemset[0]]:
IndexError: list index out of range`

**Comment by rasbt** [comment]
I think we had a small bug in this version that caused these problems sometimes. This should be fixed in the current dev version (to be released soon after I return from traveling in January). Could you check if it solves your issue when you install version 0.18dev? This can be done via 

    pip install git+git://github.com/rasbt/mlxtend.git

**Comment by MLivanos** [comment]
I do not experience the bug on the version you sent me, although I remember this error only occurred on some of my datasets. I'll be sure to update you if I encounter this error again. Thank you for your prompt response.

**Comment by rasbt** [comment]
Sounds good. I think this bug only occurred in relatively special cases, but I believe it was exactly the one we fixed. Anyways, please feel free to reopen if the error encounters with the new version.
