### ISSUE TITLE
Redeclared variable

### ISSUE THREAD

**Issue by BernoulliSanders** [rasbt/mlxtend#649]
https://github.com/rasbt/mlxtend/blob/aa47008f73e1b050dbf0532ad11ddc13e39a73f4/mlxtend/evaluate/bias_variance_decomp.py#L81

This is redeclared two lines below without being used the first time. Is this intentional?

**Comment by rasbt** [comment]
I think this must have been an error -- a line that I accidentally left in there after debugging. Will clean this up shortly. Thanks.
