### ISSUE TITLE
Possible error on weights matrix shape

### ISSUE THREAD

**Issue by GermanCM** [rasbt/mlxtend#656]
Dear Sebastian,

Having a look at the SoftmaxRegression API documentation, I see the following definition for the weights matrix in the attributes section:
*w_ : 2d-array, shape={n_features, 1}*

shouldn't it be {n_features, n_classes}
as also pointed out in the "_fit" method of the source code?

Thanks in advance,
Germán

**Comment by rasbt** [comment]
You are right; this was probably due to copy & pasting part of the (not multinomial) logistic regression code.
