### ISSUE TITLE
Comparison with sklearn's StackingClassifier

### ISSUE THREAD

**Issue by rchaves33** [rasbt/mlxtend#659]
Apologies if this is not the place for such a question, but:

What are the differences between mlxtend's `StackingCVClassifier` and sklearn's new `StackingClassifier` (which has a `cv` option)?

**Comment by rasbt** [comment]
Good question. The StackingClassifier and StackingCVClassifier in mlxtend have been around for a long time (a few years) and I assume that the new scikit-learn StackingClassifier implements the same general approach but with a slightly different API. I haven't looked at scikit-learn's stacking classifier in detail though and can't tell you much more about it.

However, when I look at the documentation, it seem that it is using cross-validation internally (the recommended approach), so it is more similar to the StackingCVClassifier in mlxtend rather then the regular StackingClassifier in mlxtend. 

I hope that helps!
