### ISSUE TITLE
Docs: incorrect image in confusion matrix example

### ISSUE THREAD

**Issue by isms** [rasbt/mlxtend#66]
**Problem:** the image for [Example 1](http://rasbt.github.io/mlxtend/user_guide/evaluate/confusion_matrix/#example-1-binary-classification) is incorrect. The given array is:

    array([[3, 1],
           [2, 2]])

Instead of showing the correct confusion matrix for the given array, the image displayed is a duplicate of the [Example 2 image](https://github.com/rasbt/mlxtend/blob/master/docs/sources/user_guide/evaluate/confusion_matrix_files/confusion_matrix_17_0.png?raw=true):

![](https://github.com/rasbt/mlxtend/blob/master/docs/sources/user_guide/evaluate/confusion_matrix_files/confusion_matrix_14_0.png?raw=true)

**Source:** appears to be cells run out of order in [confusion_matrix.ipynb](https://github.com/rasbt/mlxtend/blob/master/docs/sources/user_guide/evaluate/confusion_matrix.ipynb)

**Comment by rasbt** [comment]
Thanks a lot, should be fixed now!
