### ISSUE TITLE
McNemar's test mcnemar_table off diagonal entries are swapped

### ISSUE THREAD

**Issue by mmarius** [rasbt/mlxtend#664]
Hi Sebastian, 

the tb[1,0] and tb[0,1] entries in the 2x2 contigency table for McNemar's test in _mcnemar_table_ are swapped: https://github.com/rasbt/mlxtend/blob/master/mlxtend/evaluate/mcnemar.py#L63 

While it should not affect the test statistic, the layout is not consistent with the one you describe here: https://arxiv.org/abs/1811.12808 (Figure 19 and Figure 20)

Best,
Marius

**Comment by sankaran45** [comment]
Yes, i faced the same issue. tb[0,1] and tb[1,0] are swapped.

**Comment by rasbt** [comment]
I am just seeing this issue, thanks @mmarius and @sankaran45 . So basically you are suggesting to change the current ordering:

![mcnemar_table_13_0](https://user-images.githubusercontent.com/5618407/94343084-4fcd5980-ffdb-11ea-9ca1-d2523f3588ec.png)

such that it matches this ordering:

![mcnemar_contingency_table](https://user-images.githubusercontent.com/5618407/94343090-5956c180-ffdb-11ea-9b93-cb09bd590bfb.png)

Sure, that can be done. If you'd like to submit a PR, that'd be great.
