### ISSUE TITLE
Does StackingRegressor split data for base model and meta model?

### ISSUE THREAD

**Issue by laurence-lin** [rasbt/mlxtend#665]
I didn't see the option to split the data when using StackingRegressor(), but as I learn for non-cross-validate stacking we split the data to two part, one for base model the other for meta-model training. 

If the StackingRegressor() don't split the data, the meta-regressor receive predictions based on same data from base-model, than the whole ensemble may cause over-fitting problem.

**Comment by rasbt** [comment]
Yes, I agree that it can cause overfitting problems due to the reasons you mentioned. That's why I would recommend the `StackingCVClassifier`. If you provide your own split as `cv` argument, it would behave like you said, i.e, that the dataset is split into two but without cross-validation.
