### ISSUE TITLE
0.17.2  missing source archive on pypi

### ISSUE THREAD

**Issue by azrdev** [rasbt/mlxtend#668]
I'm packaging mlxtend for archlinux' AUR, and cannot update to 0.17.2 because the version only contains the wheel on pypi, not the source .tar.gz -- would you mind amending that archive?

I'm following https://wiki.archlinux.org/index.php/Python_package_guidelines#Source and therefore the following URL would be where I get the source: https://files.pythonhosted.org/packages/source/m/mlxtend/mlxtend-0.17.2.tar.gz

**Comment by rasbt** [comment]
Arg, my bad. Thanks for letting me now! The 0.17.2 source tar.gz should be on PyPI now!
