### ISSUE TITLE
ImportError: cannot import name 'fpmax' and fpgrowth

### ISSUE THREAD

**Issue by ZhengTzer** [rasbt/mlxtend#672]
Hi,

had installed (pip install mlxtend) in google colab,
dataframe all ready, when reached (from mlxtend.frequent_patterns import fpmax)

error message appear:
ImportError: cannot import name 'fpmax'

any idea?
thanks a lot

**same with  fpgrowth, return ImportError: cannot import name 'fpgrowth'

**Comment by rasbt** [comment]
It may be that they have an old version installed. For fpmax, you'd need to have v0.17 or higher.

Can you double check the version you are using via

```python
import mlxtend
print(mlxtend.__version__)
```

**Comment by ZhengTzer** [comment]
<img width="503" alt="mlxtend_error" src="https://user-images.githubusercontent.com/20983125/77269830-1262d900-6ce5-11ea-888c-60803054a0c5.png">

indeed, how to proceed?delete in colab and reinstall?

**Comment by rasbt** [comment]
Oh in that case there's a pretty simple fix: you just need to install the latest version in the notebook. 

You can do that by executing

```
!pip install mlxtend
```


in one of the notebook cells.

**Comment by ZhengTzer** [comment]
<img width="636" alt="mlxtend_error2" src="https://user-images.githubusercontent.com/20983125/77274804-af2b7380-6cf1-11ea-9f71-dc1e26645318.png">

thanks for your quick response, but its still the same~

**Comment by rasbt** [comment]
Ah, sorry, can you try

```
!pip install mlxtend --upgrade
```

This one should fix it. For some reason, on my local computer, I don't need the "upgrade" flag to update packages, but on Google Colab it seems to be necessary

**Comment by ZhengTzer** [comment]
fixed, thanks a lot
