### ISSUE TITLE
Gap is missing at the top of a plot_confusion_matrix and data becomes unreadable

### ISSUE THREAD

**Issue by andreamoro** [rasbt/mlxtend#679]
Have been playing around a multiclass confusion matrix. Somehow during the weekend I got updated the environment and had to reinstall all the libraries from scratch so can't produce any screenshot of what it was previously rendering correctly.

In doing so, the confusion matrix it is now plotted without gaps that makes the dataset unreadable.

![image](https://user-images.githubusercontent.com/5256583/78541257-42ce6b00-77ed-11ea-88e0-eac3fa96184e.png)

The API are quite straightforward, and I don't see what else I can change. 

```
from mlxtend.plotting import plot_confusion_matrix 
fig, ax = plot_confusion_matrix(conf_mat=cm,figsize=(12,25), class_names=numpy.unique(Y_test), show_normed=False)
ax.tick_params(axis='x', labelrotation=90)
plt.title('Confusion matrix of the classifier')
plt.show()
```

Looking at the figure side, increasing the size up to 40,40 didn't help either. The gap between each block increased, but not the one on the first line (and the last one).
A `fig.tight_layout()` didn't help either.

Removing the class names is the only chance, but this doesn't sound like an option.

Any idea?

**Comment by rasbt** [comment]
Hm that's strange, indeed. I remember that some recent matplotlib versions introduced new bugs that caused issues a couple of months back -- I forgot which version number that was though. 

Could you try the notebook at https://github.com/rasbt/mlxtend/blob/master/docs/sources/user_guide/plotting/plot_confusion_matrix.ipynb

I just tried it in matplotlib 3.1.0 and 3.1.3 and it seems to work fine.

**Comment by andreamoro** [comment]
As soon as the class_names are added, the problem presents again.

![image](https://user-images.githubusercontent.com/5256583/78670128-34f41500-78d5-11ea-9b14-6690b8f5fe2a.png)

**Comment by rasbt** [comment]
Hm, interesting. Hard to say what's going on. maybe you have one of the matplotlib versions that was buggy. I just tested this in the recent version and it seems to be fine:

![Screen Shot 2020-04-07 at 3 04 48 PM](https://user-images.githubusercontent.com/5618407/78714311-46dbb500-78e1-11ea-80ed-4c846e456c5e.png)

Could you check which matplotlib version you have?

The code example from the screenshot is below, for easier copy & pasting: 

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import mlxtend
from mlxtend.plotting import plot_confusion_matrix


multiclass = np.array([[2, 1, 0, 0],
                       [1, 2, 0, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]])

print('matplotlib version', matplotlib.__version__)
print('mlxtend version', mlxtend.__version__)

fix, ax = plot_confusion_matrix(conf_mat=multiclass,
                                colorbar=True,
                                show_absolute=False,
                                class_names=["asasasa", "asasasa", "asasasa", "asasasa"],
                                show_normed=True)

plt.show()
```

**Comment by andreamoro** [comment]
Actually, it was 3.1.1 ... updating to the 3.2.1 released yesterday apparently solves the problem.

**Comment by rasbt** [comment]
Huh, I just remembered that I filed a bug about this last year. It was specifically 3.1.1: https://github.com/matplotlib/matplotlib/issues/15733

Glad that updating fixed it.
