### ISSUE TITLE
Where is plot_sfs?

### ISSUE THREAD

**Issue by putopavel** [rasbt/mlxtend#693]
Hi,

I was reading the [SFS docs](http://rasbt.github.io/mlxtend/user_guide/feature_selection/SequentialFeatureSelector) and I saw a mention of a `plot_sfs` function under the `mlxtend.plotting` package. However, I can't import it and I didn't see such file in your repo. How can I import that function?

**Comment by putopavel** [comment]
Neverming, I just saw it was an alias for `plot_sequential_feature_selection`. My apologies.

**Comment by rasbt** [comment]
oh yeah, was importing it as `plot_sfs` for brevity reasons. Glad that there's no issue in the docs :)
