### ISSUE TITLE
Error while rendering the confusion matrix saved as .pgf in LaTeX

### ISSUE THREAD

**Issue by kanginthaya** [rasbt/mlxtend#694]
`mlxtend` is a great package, and the `plot_confusion_matrix` routine has been super useful to me. 

However, I encountered a problem when saving the confusion matrix as a pgf file and then rendering it in LaTeX. I think the issue is with `imshow` command, but just checking if you have any solution. Below is a minimum working example:

```
import matplotlib.pyplot as plt
import numpy as np
import os
from os import path
from mlxtend.plotting import plot_confusion_matrix
import matplotlib as mpl

nice_fonts = {
        "font.family" : "serif",
        "text.usetex" : True,
}

mpl.rcParams.update(nice_fonts)


fig, ax = plt.subplots(1,1)
cm = np.array([[12,18],[1,49]])
_class_labels_cm = {'class1' : 0,
                  'class2' : 1}
class_names = [k for k,v in _class_labels_cm.items()]

plot_confusion_matrix(conf_mat=cm,
                                colorbar=False,
                                show_absolute=True,
                                show_normed=False, axis = ax,hide_ticks = False,figure=fig)

fig_path = path.join(os.getcwd(),os.pardir)
fig.savefig(path.join(fig_path,'cm.pgf'), format='pgf', bbox_inches='tight')
```
Along with the pgf file, it also saves a png image of the background 'cm-img0.png' and this actually creates an issue in LaTeX. I am using LuaLaTeX to compile. Any lead is much appreciated. I am sorry if this not the right place to raise this issue since this is technically an issue with pgf and LaTeX. 

Cheers!

**Comment by kanginthaya** [comment]
Apparently the png file generated was not in the correct folder for TeX to render. Closing the issue.

**Comment by rasbt** [comment]
Glad the problem solved itself :)
