### ISSUE TITLE
Can we pass a complex Pipeline to BayesSearchCV?

### ISSUE THREAD

**Issue by kylegilde** [rasbt/mlxtend#698]
I'm trying to pass a Pipeline of pipelines and transformers to BayesSearchCV. It does "fit," but the scores are completely wrong. They increase instead of decrease and are a couple of orders of magnitude off.

Is this supposed to work? I can follow up with a reproducible example. Thanks!

pipe = Pipeline(steps=[('column_transformer', column_transformer),\
                        ('variancethreshold', VarianceThreshold(threshold=0.0)),\
                        ('selectpercentile', SelectPercentile(f_regression)),\
                       ('model', model)])

**Comment by rasbt** [comment]
Hi there,

Could you describe what you mean by "scores"? What's your performance metric? Assuming that `BayesSearchCV` follows the scikit-learn API, larger usually means better.

**Comment by kylegilde** [comment]
Never mind, I figure out my problem. Thanks!

**Comment by rasbt** [comment]
Ok, glad that you were able to solve it!
