### ISSUE TITLE
Adding scoring_func that depend on y_predict_proba to bootstrap methods

### ISSUE THREAD

**Issue by adam2392** [rasbt/mlxtend#699]
**Problem**
Currently, mlxtend bootstrapping procedures require the `scoring_func` to take `y_true` and `y_predict`. However, metrics like AUC, depend on `y_true` and `y_predict_proba` instead.

**Suggested Soln**
This could potentially be enabled by adding a kwarg to the bootstrapping functions that say `predict_proba=False` to determine which sklearn classifier prediction to use. It could be added around this line: https://github.com/rasbt/mlxtend/blob/57aa05aef85315e2dde56abc0b77e4864fde9d15/mlxtend/evaluate/bootstrap_point632.py#L162

This seems like it could potentially be an easy addition, but idk how @rasbt feels about adding an additional kwarg to the bootstrapping funcs?

**Misc**
I can submit a PR if so. Lmk if you want me to add any unit tests as well?

**Comment by rasbt** [comment]
This sounds like a useful and elegant solution indeed. I am in favor of this and would thankful about a PR. If you have the time for this PR and could add unit tests, that would be great -- so far, the goal in mlxtend is to have unit tests for as much as possible.
