### ISSUE TITLE
ci_bound unique value

### ISSUE THREAD

**Issue by Icron1** [rasbt/mlxtend#702]
Hi,

I have a question about returned values from the Sequentiel Feature Selector.
When performed with cross-validation, it provides a scoring criterion value and a unique ci_bound value.
I read in the doc that is was the 95CI value.
But how should we interpret this unique value?

Let's say scoring 0.8, ci_bound 0.2 ... does that mean 0.8 (95CI 0.78-0.82)? or (0.79-0.81)? Or something else? It's not clear to me.

Thanks
Loïc

**Comment by rasbt** [comment]
Hi Loïc,

> Let's say scoring 0.8, ci_bound 0.2 ..

in this case, this would mean that the confidence interval (95% by default) would range from 0.6 to 1.0. I hope this clarifies it. Otherwise, please let me know :)

**Comment by Icron1** [comment]
Hi rasbt,

Thank you! That clear now.
