### ISSUE TITLE
FPMax Wrong Support?

### ISSUE THREAD

**Issue by shenxiangzhuang** [rasbt/mlxtend#709]
## Test Dataset
I'm using the mushroom dataset which can be found at [here](https://github.com/felipekunzler/frequent-itemset-mining-spark/tree/master/src/main/resources/datasets)

## Versions
Python=3.7.6
mlxtend=0.17.2

## Test Code

```python
# coding=utf-8
import numpy as np
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpmax


# mushroom dataset
mushroomdata = []
with open("mushroom.txt", "r") as f:
    for line in f.readlines():
        nums = [int(c) for c in line.strip("\n").split(" ") if c != "" and c != "\r"]
        mushroomdata.append(nums)
# trans
te = TransactionEncoder()
mushroomTeArray = te.fit(mushroomdata).transform(mushroomdata)
mushroomDf = pd.DataFrame(mushroomTeArray, columns=te.columns_)
# MFI, min-sup = 0.3
mushroomMfIDf = fpmax(mushroomDf, min_support=0.3, use_colnames=True)
mushroomMfIDf["count"] = len(mushroomdata) * mushroomMfIDf.support
mushroomMFI = mushroomMfIDf[["itemsets", "count"]]
mushroomMFI["itemsets"] = mushroomMFI["itemsets"].apply(lambda x: tuple(sorted(x)))

```
And the last output is `(34, 39, 59, 63, 85, 86, 90)`  with a support `2696.0`. BUT, the true support of the MFI is `2504`.
```python
i = 0                                                                                                                                                                                              
for row in mushroomdata: 
    if len(set(row) & {34, 39, 59, 63, 85, 86, 90}) == 7: 
        i += 1 
print(i)
```

**Comment by rasbt** [comment]
Hi there. 

Unfortunately, there was a bug in 0.17.2 that could lead to wrong support via fpmax some times. Thanks to @harenbergsd, this was fixed recently. However, I haven't made a new release version of mlxtend, yet. I am currently traveling but will put that onto my todo list for late July when I am back at a "real" computer. 

In the meantime you could install and use the latest development version. It can be installed via

    pip install git+git://github.com/rasbt/mlxtend.git

Let me know if that works for you.

**Comment by rasbt** [comment]
Should be fixed now in the new 0.17.3 release.

**Comment by shenxiangzhuang** [comment]
Yes, it works and I can get right support count now. Thanks for your reply.

**Comment by rasbt** [comment]
glad to hear it works now!
