### ISSUE TITLE
Invalid permutation test ?

### ISSUE THREAD

**Issue by DarthTrevis** [rasbt/mlxtend#718]
Hello,

I was glad to find an implementation of permutation tests to challenge my theoretical understanding of it (and compare with my own).

Actually, it seems that `mlxtend.evaluate.permutation_test` wrongly rejects permutations whose statistic result is equal to the tested statistic (exact tests [here ](https://github.com/rasbt/mlxtend/blob/master/mlxtend/evaluate/permutation.py#L123) and simulations [here](https://github.com/rasbt/mlxtend/blob/master/mlxtend/evaluate/permutation.py#L131)), which leads to lower p-values than desired.

The fix is quite simple. Should I open a PR ? Or did I miss something ?

Thanks

**Comment by rasbt** [comment]
Good catch and thanks for the note. It should indeed be "greater or equal to" (`>=`). If you'd like to open a PR, that'd be nice.
