### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by jaimebayes** [rasbt/mlxtend#723]
Hi, 

I am trying to use this package in google colab notebook, but it shows this error.
ImportError: cannot import name 'bias_variance_decomp'
Any idea how to fix it?

Thanks in advance, JL

**Comment by rasbt** [comment]
I think I've seen this before. I think Google Colab has an old version pre-installed. Can you try to install the latest version? I.e., execute the command

```
!pip install mlxtend
```

in a separate cell and then try again. Please let me know if that works.

**Comment by rasbt** [comment]
Hm, Google Colab seems to have some weird behavior compared to regular Jupyter Notebooks, but 

    %pip install mlxtend --upgrade

should do the job:

![Screen Shot 2020-08-24 at 9 14 57 AM](https://user-images.githubusercontent.com/5618407/91055563-723e1280-e5ea-11ea-9364-0ec5a6c00ad4.png)

The version should be 0.17.3 afterwards:

![Screen Shot 2020-08-24 at 9 15 17 AM](https://user-images.githubusercontent.com/5618407/91055572-7407d600-e5ea-11ea-9151-000aed73a3e9.png)

**Comment by jaimebayes** [comment]
Thanks Sebastian @rasbt, your suggestion works fine, 

JL
