### ISSUE TITLE
should dlib scikit-image be listed in requirements.txt?

### ISSUE THREAD

**Issue by suliuzh** [rasbt/mlxtend#724]
#### Describe the documentation issue
Hi
some dependencies such as **dlib** are listed in _.travis.yml_. But it is used in source code files like this in the following. If it is a must,  I am wondering if such dependencies should be listed in setup.py or requirements.txt? 
![image](https://user-images.githubusercontent.com/27858725/91736064-ba0efc00-ebdf-11ea-8122-f15248e0ae2f.png)

**Comment by rasbt** [comment]
Good point. `dlib` is only required for some of the mlxtend.image functions. However, dlib installation causes problems on some computers, and only a very, very small number of people are using the dlib-dependent functions of mlxtend in mlxtend.image, so I didn't want to make it a requirement in setup.py.
