### ISSUE TITLE
TypeError: axis() got an unexpected keyword argument 'y_min' 

### ISSUE THREAD

**Issue by koushikam** [rasbt/mlxtend#735]
Hi I am having the following issue since conda package update

**TypeError: axis() got an unexpected keyword argument 'y_min'**

Priviously I could able to run and see my results..

Even I tried with one of examples in the mlxtend page. This also has the same error:

import matplotlib.pyplot as plt
from mlxtend.plotting import plot_decision_regions

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB 
from sklearn import datasets
import numpy as np

# Loading some example data
iris = datasets.load_iris()
X = iris.data[:, 2]
X = X[:, None]
y = iris.target

# Initializing and fitting classifiers
clf1 = LogisticRegression(random_state=1,
                          solver='lbfgs',
                          multi_class='multinomial')
clf2 = GaussianNB()
clf1.fit(X, y)
clf2.fit(X, y)

fig, axes = plt.subplots(1, 2, figsize=(10, 3))

fig = plot_decision_regions(X=X, y=y, clf=clf1, ax=axes[0], legend=2)
fig = plot_decision_regions(X=X, y=y, clf=clf2, ax=axes[1], legend=1)

plt.show()

**Comment by rasbt** [comment]
Hi there,

I think this may be to an mlxtend version issue. The example above works in my latest version. Let me know if you need more help with that.

**Comment by sabarezaeii** [comment]
Hello, 
I am having the same issue. 
I am trying to run a very simple example to check **plot_decision_regions** and I get the following error:



axis() got an unexpected keyword argument 'y_min'

my code: 


X = np.array([[0.3,1],[0.5,4.5],[1,2.3],[1.4,1.9],[1.7,8.9],[2,4.1],[3.3,7],[3.5,1.5],[4,6.3],[4.4,1.9],[5.7,2.9],[6,7.1]])
y = np.array([0,0,0,0,0,0,1,1,1,1,1,1])
plot_decision_regions( X, y, clf=classifier, legend=2)


plt.show()
