### ISSUE TITLE
plot_confusion_matrix() gets TypeError on class_names

### ISSUE THREAD

**Issue by MauricePonte** [rasbt/mlxtend#736]
#### Describe the bug

plot_confusion_matrix() got an unexpected keyword argument 'class_names'

#### Steps/Code to Reproduce

```python
import mlxtend.plotting as plotting
import matplotlib.pyplot as plt
import numpy as np

binary1 = np.array([[40, 3],
                    [ 4,23]])
names = ['Spam','Not spam']

fig, ax = plotting.plot_confusion_matrix(conf_mat=binary1, class_names = names)
plt.show()
```

#### Actual Results

TypeError                             
Traceback (most recent call last)
      names = ['Spam','Not spam']
--->fig, ax = plotting.plot_confusion_matrix(conf_mat=binary1, class_names = names)
       plt.show()

TypeError: plot_confusion_matrix() got an unexpected keyword argument 'class_names'

MLxtend 0.14.0
Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
Scikit-learn 0.22.2.post1
NumPy 1.18.5
SciPy 1.4.1

**Comment by rasbt** [comment]
Hi there. The `class_names` parameter was added in v0.17.2. If you upgrade to v0.17.2 or v0.17.3, this should work.
