### ISSUE TITLE
Sequential Feature Selector confusing notation

### ISSUE THREAD

**Issue by theinem** [rasbt/mlxtend#738]
In the page "Sequential Feature Selector" 
[http://rasbt.github.io/mlxtend/user_guide/feature_selection/SequentialFeatureSelector/](url)

I am trying to understand the SFFS section, and the notation seems to be wrong, i.e., the condition if `J(xk−x)>J(xk−x)` will always be false because the left side and the right side are the same. I think there's an error confusing `Xk` with `xk`, but I'm not sure.

I want to write my won algorithm, any advice will be appreciated too.

**Comment by rasbt** [comment]
Thanks for the note

(1) Yeah, I think that I've been inconsistent with the use of Xk with xk when inside J(...)

(2) good call. Should be J(Xk−x)>J(Xk) instead of J(Xk−x)>J(Xk−x)

Will fix those. The change won't be reflected on the website docs until the next version release though.
