### ISSUE TITLE
Apply create_counterfactual method to regression task? 

### ISSUE THREAD

**Issue by MauroLuzzatto** [rasbt/mlxtend#758]
Thanks a lot, to the creators for the nice implementation of the `create_counterfactual `! 

I was wondering, if it is reasonable to use the implementation also for regression task? As for example if `y_desired` could also be a float, which should be reached?
I tried it out and the results seem reasonable, nevertheless, I quickly want to ask, if this usage would make sense.
Thanks a lot!

**Comment by rasbt** [comment]
yeah, I think this would generally work. In practice it may be trickier though due to the nature of regression values (compared to class label probabilities in range (0, 1)). The implementation may have to be slightly tweaked for regression but I am not 100% sure; haven't tried.

**Comment by MauroLuzzatto** [comment]
Great, thanks for the fast response. I will look into this!
