### ISSUE TITLE
'StackingClassifier' object has no attribute 'clf_'

### ISSUE THREAD

**Issue by charleshm** [rasbt/mlxtend#76]
`sclf = StackingClassifier(classifiers=[clf1, clf2, clf3],
                          meta_classifier=lr, use_probas=True, verbose=1)`

when I set use_probas=True, I got these.

> AttributeError:'StackingClassifier' object has no attribute 'clf_'

what should I do?

**Comment by rasbt** [comment]
Hi, @charleshm,
I just see that there was a dumb typo in the `verbose` option that causes this `AttributeError`. I fixed it in #77  and will merge once the Travis tests are finished. Thanks for the note!
