### ISSUE TITLE
Stratified cross-validation in both StackingCVClassifier and GridSearchCV?

### ISSUE THREAD

**Issue by antranttu** [rasbt/mlxtend#770]
Hello,

I'm working on a super imbalanced dataset, and I'm doing resampling during Stacked CV Classification combined with GridSearch to search for the best hyperparameters. I was wondering if I need to pass my `StratifiedKFold` object as arguments in both `StackingCVClassifier` and `GridSearchCV`, or just one of the two will suffice?

Thank you!

**Comment by rasbt** [comment]
Good question. StackingCVClassifier should use stratified k-fold by default when you set `cv` to some integer value (or leave the default). 

As far as I know, GridSearchCV performs stratified k-fold as well, so you don't need to pass StratifiedKFold manually.

Hope that helps!
