### ISSUE TITLE
moving stuff upstream

### ISSUE THREAD

**Issue by amueller** [rasbt/mlxtend#8]
hey. Do you want to move some of this stuff upstream?
I wanted to have a general decision region /  decision boundary function because it is reimplemented in soo many examples.

**Comment by rasbt** [comment]
Hi, Andreas,
sure, I am always really happy to contribute to scikit-learn -- this library helped me so much that I am really looking forward to help. I put up this mlxtend lib for things that I "immediately" need so it's probably not the nicest code, but I guess we can work on that ;) I will open a pull request on the sklearn repo and we can discuss this further.

**Comment by rasbt** [comment]
Which submodule do you have in mind? `classification`, `utils`, or maybe a new `visualization` module (for adding other things later, e.g,. silhouette plots for clustering etc)?

**Comment by amueller** [comment]
I was thinking about utils, maybe utils.plotting. It is not really very general.

**Comment by rasbt** [comment]
Sounds good! I will prepare a pull request in the next couple of days!
