### ISSUE TITLE
shuffle_arrays_unison: inconsistency in the random state parameter

### ISSUE THREAD

**Issue by chkoar** [rasbt/mlxtend#81]
The random state parameter in `shuffle_arrays_unison` function is `random_seed` but in the docstring it is named `random_state`. The same exists in the docs http://rasbt.github.io/mlxtend/user_guide/preprocessing/shuffle_arrays_unison/. I would make a PR but I don't know what we want to keep.

**Comment by rasbt** [comment]
Thanks! 

> http://rasbt.github.io/mlxtend/user_guide/preprocessing/shuffle_arrays_unison/. I would make a PR but I don't know what we want to keep.

It should be `random_seed` to be consistent with all other functions. If I see it correctly, the function param and the docstring param sections are fine but the typo occurs in the examples section -- there are currently no unit tests for the examples. 
Let me know if you like to submit a pull request (basically, you just need to update the docstring and run the "make_api" script) from the docs directory. I can take care of the IPython notebook and upload to the webserver afterwards.

**Comment by chkoar** [comment]
Is `make_api` compatible only with `py35`?  I'll open a PR.

**Comment by rasbt** [comment]
Yes may only be py35 compatible. I didn't bother making it py27 compatible since it's only run by me internally so far. You are very welcome to tweak it for py27 compatibility though if you like

**Comment by rasbt** [comment]
fixed in #87
