### ISSUE TITLE
Incorrect Documentation about Support for Association Rules

### ISSUE THREAD

**Issue by BrunoBarre** [rasbt/mlxtend#849]
Hello,

There seems to be an incoherence in the support metric description for association rules in this page [http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/#example-3-frequent-itemsets-with-incomplete-antecedent-and-consequent-information](http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/#example-3-frequent-itemsets-with-incomplete-antecedent-and-consequent-information).

The formula is correct : `support(A→C)=support(A∪C),range: [0,1].` But in the following paragraph, it is written `The 'support' metric then computes the support of the combined itemset A ∪ C -- note that 'support' depends on 'antecedent support' and 'consequent support' via min('antecedent support', 'consequent support').` Which is clearly different from the formula.

In `mlxtend.frequent_patterns.association_rules` support is computed using the formula, and not the minimum between the antecedent support and consequent support.

**Comment by zuari1993** [comment]
Hi, 
Thanks for pointing this out. 
You are correct on the inconsistency.
I will work on fixing this.
