### ISSUE TITLE
Wrong Itemsets when compare the df with Aprori and FP growth 

### ISSUE THREAD

**Issue by jahidhasanlinix** [rasbt/mlxtend#869]
### Discussed in https://github.com/rasbt/mlxtend/discussions/868

<div type='discussions-op-text'>

<sup>Originally posted by **jahidhasanlinix** December  7, 2021</sup>
I was following the mlxtend docs to do the experiment on Apriori and FP growth and compare it but it seems I am getting different itemsets where it should be the same as I use the same df. Any suggestions why this occurring?

**### Aprori:**
![screenshot](https://user-images.githubusercontent.com/36171973/145144315-4bcd580e-15ca-4921-b152-fce98d99a80c.png)
![screenshot_1](https://user-images.githubusercontent.com/36171973/145144325-ea2067a1-a647-415d-9cec-938284af1817.png)

**### FP Growth part:**
![screenshot_2](https://user-images.githubusercontent.com/36171973/145144362-68669d44-3b85-46b1-9b93-633d57630184.png)
![screenshot_3](https://user-images.githubusercontent.com/36171973/145144364-5dc904d9-bbdd-480e-9439-d8dfd1298ee7.png)

</div>

**Comment by rasbt** [comment]
Closing since we have the related discussion. Happy to reopen if this turns out to be a bug.
