### ISSUE TITLE
Additional whitespace in the link takes the users to 404 not found page

### ISSUE THREAD

**Issue by odk-chuky** [rasbt/mlxtend#890]
#### Describe the documentation issue

Under this document http://rasbt.github.io/mlxtend/api_subpackages/mlxtend.frequent_patterns/, there's a URL to see more information about pandas Sparse data structure (`https://pandas.pydata.org/pandas-docs/stable/ user_guide/sparse.html#sparse-data-structures`). Since there's additional whitespace before `user_guide` it's unable to find the right page. 

#### Suggest a potential improvement or addition

By simply removing the whitespace, I could go to the page I wanted. 

https://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#sparse-data-structures

**Comment by rasbt** [comment]
Thanks for the note! Just went ahead and fixed that. I really need to improve the docstring-to-markdown parser some time.
