### ISSUE TITLE
 EnsembleClassifier with scaled and unscaled data

### ISSUE THREAD

**Issue by ibanez4510** [rasbt/mlxtend#9]
Hello,
I am training and fitting data using different classifieres. For some of them (eg. Multi-layer perceptron) I scale the training and testing matrices using scikits StandardScaler(). For others (eg. Random Forest) I do not scale the data.

I would like to use the EnsembleClassifier and was wondering how to use it with classifiers that were trained with different matrices (scaled vs unscaled).

Thanks!

**Comment by rasbt** [comment]
Hi,
have you tried to provide classifier-pipelines as input? E.g.,

    mlp = Pipeline([('std', StandardScaler()), 
                           ('mlp', MultiLayerPerceptron())])

Pls let me know if it works.

Or in case of the random forest, it may be easiest to train it with the scaled data as well (should yield the same results).

**Comment by ibanez4510** [comment]
Thanks for the reply!

I will look into your suggestion

**Comment by ibanez4510** [comment]
I get very similar results using scaled data across the board. I can now use the EnsembleClassifier. Thanks again!

**Comment by rasbt** [comment]
Cool, I am happy to hear that it worked out for you!
