### ISSUE TITLE
Set up black for code formatting

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#911]
It would be nice to automatically use [black](https://black.readthedocs.io/en/stable/) to make the code style consistent. 

#### Describe the workflow you want to enable

When someone submits a PR, black should take care of the style fixing.

**Comment by NimaSarajpoor** [comment]
I was wondering if black can fix things completely in an automated manner. I have been contributing to STUMPY library and what I realized there was that we had to check code format with black and then we had to correct the format and run the black test again. Maybe I am missing something.

**Comment by rasbt** [comment]
@NimaSarajpoor Ah yes, you are right, I tried it the other day here #914 and it is exactly like you said.

**Comment by rasbt** [comment]
I added it as an experiment. If that's too annoying, I guess we can remove it again in the future 😅

**Comment by NimaSarajpoor** [comment]
@rasbt 
Cool. I checked out the in the contributor guide. 

Just a suggestion: You may want to add to the `contributor guide` that the contributors should do `git add` and `git commit` after correcting the format with black, before pushing it to the upstream.

**Comment by rasbt** [comment]
Good call! I will add it!

**Comment by labdmitriy** [comment]
> I added it as an experiment. If that's too annoying, I guess we can remove it again in the future sweat_smile

Could you please explain why it can be annoying?
As I understand, you are using official black GitHub Action, and it will run black with --diff and --check options, and only reports if it is formatted or not, and will prevent using of not formatted code for events you specified (pull request / push). And different tools on contributors side (IDE configuration, pre-commit hooks) will prepare the code using required rules.

**Comment by rasbt** [comment]
So with annoying I meant that it could be too much for some contributors. Like adding too much of a barrier to entry when making PRs. Because black is stricter than just PEP8

**Comment by labdmitriy** [comment]
> So with annoying I meant that it could be too much for some contributors. Like adding too much of a barrier to entry when making PRs. Because black is stricter than just PEP8

I understand, thank you!
But probably it will help in the future with consistent code style and save your time in reviews :)

**Comment by rasbt** [comment]
Oh yes that's for sure! Basically, what I meant was: It's a great idea, but let's see how that will work out in practice ;)
Btw I updated the Quick Contributor Guide here: http://rasbt.github.io/mlxtend/CONTRIBUTING/ to make it a bit more clear how things work now
