### ISSUE TITLE
Decision region plot for more than 4 classes 

### ISSUE THREAD

**Issue by rasbt** [rasbt/mlxtend#97]
I am not 100% sure if this is a bug in matplotlib, but I would appreciate any helps or insights. There may be a work-around for solving the problem below, but I haven't found it, yet. (Also see this [matplotlib discussion](https://github.com/matplotlib/matplotlib/issues/7103#issuecomment-246759376) as reference.

The following code -- plotting 4 decision regions -- works just fine (1, 2, and 3 classes work fine as well):

(Note that the code below is a simplified version of the `plot_decision_regions` plot in mlxtend. If we can fix this simple issue below -- I think it is related to the ListedColormap -- it can be directly transferred to the `plot_decsion_regions` function)

```python
from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression

def plot_decision_regions(X, y, classifier, resolution=0.1):

    # setup marker generator and color map
    markers = ('s', 'x', 'o', '^', 'v')
    colors = ('red', 'blue', 'lightgreen', 'gray', 'cyan')
    cmap = ListedColormap(colors[:len(np.unique(y))+1])

    # plot the decision surface
    x1_min, x1_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    x2_min, x2_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx1, xx2 = np.meshgrid(np.arange(x1_min, x1_max, resolution),
                           np.arange(x2_min, x2_max, resolution))
    Z = classifier.predict(np.array([xx1.ravel(), xx2.ravel()]).T)
    Z = Z.reshape(xx1.shape)
    plt.contourf(xx1, xx2, Z, alpha=0.4, cmap=cmap)
    plt.xlim(xx1.min(), xx1.max())
    plt.ylim(xx2.min(), xx2.max())

    # plot class samples
    for idx, cl in enumerate(np.unique(y)):
        plt.scatter(x=X[y == cl, 0], y=X[y == cl, 1],
                    alpha=0.8, c=colors[idx],
                    marker=markers[idx], label=cl)


# Loading some example data
iris = datasets.load_iris()
X = iris.data[:, [0,2]]
y = iris.target
y = np.concatenate((y, np.ones(50)+2))
y = y.astype(int)
X = np.concatenate((X, X[:50]*2))

lr = LogisticRegression(solver='newton-cg', multi_class='multinomial')
lr.fit(X, y)
plot_decision_regions(X, y, classifier=lr)
```

![983261a2-79a2-11e6-96b6-1443342eb519](https://cloud.githubusercontent.com/assets/5618407/18497025/079e598c-79f9-11e6-9161-3e2d90bfce1b.png)

However, if I add a third class, I get the following problem:

```python
iris = datasets.load_iris()
X = iris.data[:, [0,2]]
y = iris.target
y = np.concatenate((y, np.ones(50)+2, np.ones(50)+3))
y = y.astype(int)
X = np.concatenate((X, X[:50]*2, X[:50]*3))

lr = LogisticRegression(solver='newton-cg', multi_class='multinomial')
lr.fit(X, y)
plot_decision_regions(X, y, classifier=lr)
```

![bb64190e-79a2-11e6-88be-8ebd713cde67](https://cloud.githubusercontent.com/assets/5618407/18497041/266081f6-79f9-11e6-8fc9-0252e82a3bbf.png)

**Comment by AlphaRandom** [comment]
I think there could be a bug anytime you pass on a classifier trained on more than two features. In fact in this case I have to use both filler_feature_values and filler_feature_ranges and also feature_index. Result always shows only 3 decision regions, while if I pass same classifier only trained on two features I can see four regions as expected. Do I need to open a bug?
