### ISSUE TITLE
Possible mistake in paired_ttest_resampled doc

### ISSUE THREAD

**Issue by Hardwarize** [rasbt/mlxtend#975]
#### Describe the documentation issue

I think that there is an error in the T-value formula in the Resampled paired t test doc page.
<img width="507" alt="image" src="https://user-images.githubusercontent.com/105778395/195056308-512f8c7f-cffa-4822-9d5a-7855627b4277.png">

It seems that, in the denominator, p is raised to (i) - p

#### Suggest a potential improvement or addition

I think that this:
$$t = \\frac{\\overline{p} \\sqrt{k}}{\\sqrt{\\sum_{i=1}^{k}(p^{(i) - \\overline{p}})^2 / (k-1)}}.$$

should be replace by this:
$$t = \\frac{\\overline{p} \\sqrt{k}}{\\sqrt{\\sum_{i=1}^{k}(p^{(i)} - \\overline{p})^2 / (k-1)}}.$$

Thanks for this amazing library!

**Comment by rasbt** [comment]
Thanks a lot for the note! You are right, that was a formatting issue. Just fixed it via #976
